// Maps ISO 3166-1 alpha-2 country codes (as used in Ratehawk's `region.country_code`)
// to the exact country-name strings used in the OLTRA `hotels` collection.
export const ISO2_TO_OLTRA_COUNTRY = {
  AG: "Antigua & Barbuda",
  AI: "Anguilla",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BB: "Barbados",
  BT: "Bhutan",
  BW: "Botswana",
  BR: "Brazil",
  VG: "British Virgin Islands",
  KH: "Cambodia",
  CA: "Canada",
  KY: "Cayman Islands",
  CL: "Chile",
  CN: "China",
  HK: "China",
  MO: "China",
  CR: "Costa Rica",
  HR: "Croatia",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DO: "Dominican Republic",
  EG: "Egypt",
  EC: "Equador",
  FJ: "Fiji",
  FR: "France",
  PF: "French Polynesia",
  DE: "Germany",
  GR: "Greece",
  GD: "Grenada",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  KE: "Kenya",
  LA: "Laos",
  MY: "Malaysia",
  MV: "Maldives",
  MU: "Mauritius",
  MX: "Mexico",
  MC: "Monaco",
  ME: "Montenegro",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NP: "Nepal",
  NL: "Netherlands",
  NZ: "New Zealand",
  NO: "Norway",
  OM: "Oman",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  RS: "Serbia",
  SC: "Seychelles",
  SG: "Singapore",
  ZA: "South Africa",
  KR: "South Korea",
  ES: "Spain",
  BL: "St. Barthelemy",
  LC: "St. Lucia",
  MF: "St. Martin",
  VC: "St. Vincent and the Grenadines",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  TZ: "Tanzania",
  TH: "Thailand",
  TR: "Turkey",
  TC: "Turks & Caicos Islands",
  US: "USA",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  UY: "Uruguay",
  VN: "Vietnam",
  ZW: "Zimbabwe",
};
