import type { InspireMonth, InspirePurpose } from "./types";

type CityMetadata = {
  city: string;
  country: string;
  lat: number;
  lng: number;
  purposes: InspirePurpose[];
  coastal: boolean;
  ski: boolean;
  monthlyAvgTempC: Record<InspireMonth, number>;
};

export const INSPIRE_CITY_METADATA: CityMetadata[] = [
  {
    city: "Lisbon",
    country: "Portugal",
    lat: 38.7223,
    lng: -9.1393,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 11,
      february: 12,
      march: 14,
      april: 16,
      may: 19,
      june: 22,
      july: 25,
      august: 26,
      september: 24,
      october: 20,
      november: 15,
      december: 12,
    },
  },
  {
    city: "Marrakech",
    country: "Morocco",
    lat: 31.6295,
    lng: -7.9811,
    purposes: ["city_break", "mountains"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 12,
      february: 14,
      march: 17,
      april: 19,
      may: 23,
      june: 27,
      july: 31,
      august: 31,
      september: 27,
      october: 22,
      november: 17,
      december: 13,
    },
  },
  {
    city: "Geneva",
    country: "Switzerland",
    lat: 46.2044,
    lng: 6.1432,
    purposes: ["city_break", "ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: 2,
      february: 4,
      march: 8,
      april: 11,
      may: 16,
      june: 20,
      july: 23,
      august: 22,
      september: 18,
      october: 13,
      november: 7,
      december: 3,
    },
  },
  {
    city: "Dubai",
    country: "UAE",
    lat: 25.2048,
    lng: 55.2708,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 19,
      february: 20,
      march: 23,
      april: 27,
      may: 31,
      june: 33,
      july: 35,
      august: 35,
      september: 33,
      october: 30,
      november: 25,
      december: 21,
    },
  },
  {
    city: "Malé",
    country: "Maldives",
    lat: 4.1755,
    lng: 73.5093,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 28,
      march: 29,
      april: 30,
      may: 30,
      june: 29,
      july: 29,
      august: 29,
      september: 29,
      october: 28,
      november: 28,
      december: 27,
    },
  },
  {
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    purposes: ["beach", "city_break", "mountains", "safari"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 22,
      february: 22,
      march: 21,
      april: 18,
      may: 16,
      june: 13,
      july: 13,
      august: 14,
      september: 15,
      october: 17,
      november: 19,
      december: 21,
    },
  },
  {
    city: "Nairobi",
    country: "Kenya",
    lat: -1.2921,
    lng: 36.8219,
    purposes: ["safari", "city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 20,
      february: 21,
      march: 21,
      april: 20,
      may: 18,
      june: 17,
      july: 16,
      august: 17,
      september: 19,
      october: 20,
      november: 19,
      december: 20,
    },
  },
  {
    city: "London",
    country: "England",
    lat: 51.5072,
    lng: -0.1276,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 5,
      february: 6,
      march: 8,
      april: 10,
      may: 14,
      june: 17,
      july: 19,
      august: 19,
      september: 16,
      october: 12,
      november: 8,
      december: 6,
    },
  },
  {
    city: "New York",
    country: "USA",
    lat: 40.7128,
    lng: -74.006,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 1,
      february: 3,
      march: 7,
      april: 13,
      may: 18,
      june: 24,
      july: 27,
      august: 26,
      september: 22,
      october: 16,
      november: 10,
      december: 5,
    },
  },
  {
    city: "Paris",
    country: "France",
    lat: 48.8566,
    lng: 2.3522,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 5,
      february: 6,
      march: 9,
      april: 12,
      may: 16,
      june: 20,
      july: 23,
      august: 23,
      september: 19,
      october: 14,
      november: 9,
      december: 6,
    },
  },
  {
    city: "Bangkok",
    country: "Thailand",
    lat: 13.7563,
    lng: 100.5018,
    purposes: ["city_break", "beach"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 29,
      march: 30,
      april: 31,
      may: 30,
      june: 30,
      july: 29,
      august: 29,
      september: 28,
      october: 28,
      november: 28,
      december: 27,
    },
  },
  {
    city: "Rome",
    country: "Italy",
    lat: 41.9028,
    lng: 12.4964,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 8,
      february: 9,
      march: 11,
      april: 14,
      may: 18,
      june: 23,
      july: 26,
      august: 26,
      september: 22,
      october: 17,
      november: 12,
      december: 9,
    },
  },
  {
    city: "Courchevel 1850",
    country: "France",
    lat: 45.4154,
    lng: 6.6346,
    purposes: ["ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: -4,
      february: -3,
      march: 0,
      april: 3,
      may: 8,
      june: 12,
      july: 15,
      august: 15,
      september: 11,
      october: 6,
      november: 0,
      december: -3,
    },
  },
  {
    city: "Hong Kong",
    country: "China",
    lat: 22.3193,
    lng: 114.1694,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 16,
      february: 17,
      march: 20,
      april: 23,
      may: 27,
      june: 29,
      july: 30,
      august: 29,
      september: 28,
      october: 26,
      november: 22,
      december: 18,
    },
  },
  {
    city: "Abu Dhabi",
    country: "UAE",
    lat: 24.4539,
    lng: 54.3773,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 20,
      february: 21,
      march: 24,
      april: 29,
      may: 33,
      june: 35,
      july: 37,
      august: 37,
      september: 35,
      october: 32,
      november: 27,
      december: 22,
    },
  },
  {
    city: "Shanghai",
    country: "China",
    lat: 31.2304,
    lng: 121.4737,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 5,
      february: 7,
      march: 10,
      april: 16,
      may: 21,
      june: 25,
      july: 29,
      august: 29,
      september: 25,
      october: 20,
      november: 14,
      december: 8,
    },
  },
  {
    city: "Tokyo",
    country: "Japan",
    lat: 35.6762,
    lng: 139.6503,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 6,
      february: 7,
      march: 10,
      april: 15,
      may: 19,
      june: 22,
      july: 26,
      august: 27,
      september: 24,
      october: 18,
      november: 13,
      december: 8,
    },
  },
  {
    city: "Beijing",
    country: "China",
    lat: 39.9042,
    lng: 116.4074,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: -3,
      february: 1,
      march: 8,
      april: 15,
      may: 21,
      june: 26,
      july: 27,
      august: 26,
      september: 21,
      october: 14,
      november: 5,
      december: -1,
    },
  },
  {
    city: "Chicago",
    country: "USA",
    lat: 41.8781,
    lng: -87.6298,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: -3,
      february: -1,
      march: 4,
      april: 10,
      may: 16,
      june: 22,
      july: 24,
      august: 24,
      september: 20,
      october: 13,
      november: 6,
      december: 0,
    },
  },
  {
    city: "Milan",
    country: "Italy",
    lat: 45.4642,
    lng: 9.19,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 3,
      february: 6,
      march: 10,
      april: 14,
      may: 19,
      june: 23,
      july: 26,
      august: 25,
      september: 21,
      october: 15,
      november: 9,
      december: 4,
    },
  },
  {
    city: "Las Vegas",
    country: "USA",
    lat: 36.1699,
    lng: -115.1398,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 9,
      february: 12,
      march: 16,
      april: 21,
      may: 27,
      june: 33,
      july: 37,
      august: 36,
      september: 31,
      october: 23,
      november: 15,
      december: 9,
    },
  },
  {
    city: "Madrid",
    country: "Spain",
    lat: 40.4168,
    lng: -3.7038,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 6,
      february: 8,
      march: 11,
      april: 13,
      may: 18,
      june: 23,
      july: 27,
      august: 27,
      september: 22,
      october: 16,
      november: 10,
      december: 7,
    },
  },
  {
    city: "Venice",
    country: "Italy",
    lat: 45.4408,
    lng: 12.3155,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 4,
      february: 6,
      march: 9,
      april: 13,
      may: 18,
      june: 22,
      july: 25,
      august: 25,
      september: 21,
      october: 15,
      november: 9,
      december: 5,
    },
  },
  {
    city: "Barcelona",
    country: "Spain",
    lat: 41.3874,
    lng: 2.1686,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 10,
      february: 11,
      march: 13,
      april: 15,
      may: 18,
      june: 22,
      july: 25,
      august: 26,
      september: 23,
      october: 19,
      november: 14,
      december: 11,
    },
  },
  {
    city: "Florence",
    country: "Italy",
    lat: 43.7696,
    lng: 11.2558,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 6,
      february: 8,
      march: 11,
      april: 14,
      may: 18,
      june: 22,
      july: 25,
      august: 25,
      september: 21,
      october: 16,
      november: 10,
      december: 7,
    },
  },
  {
    city: "Miami Beach",
    country: "USA",
    lat: 25.7907,
    lng: -80.13,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 20,
      february: 21,
      march: 23,
      april: 25,
      may: 27,
      june: 29,
      july: 30,
      august: 30,
      september: 29,
      october: 27,
      november: 24,
      december: 21,
    },
  },
  {
    city: "Riviera Maya",
    country: "Mexico",
    lat: 20.6296,
    lng: -87.0739,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 23,
      february: 24,
      march: 25,
      april: 27,
      may: 28,
      june: 28,
      july: 29,
      august: 29,
      september: 28,
      october: 27,
      november: 25,
      december: 24,
    },
  },
  {
    city: "Singapore",
    country: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 28,
      march: 28,
      april: 29,
      may: 29,
      june: 28,
      july: 28,
      august: 28,
      september: 28,
      october: 28,
      november: 27,
      december: 27,
    },
  },
  {
    city: "St. Moritz",
    country: "Switzerland",
    lat: 46.497,
    lng: 9.838,
    purposes: ["ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: -7,
      february: -6,
      march: -3,
      april: 0,
      may: 5,
      june: 9,
      july: 12,
      august: 11,
      september: 8,
      october: 3,
      november: -2,
      december: -5,
    },
  },
  {
    city: "Amsterdam",
    country: "Netherlands",
    lat: 52.3676,
    lng: 4.9041,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 4,
      february: 4,
      march: 7,
      april: 10,
      may: 14,
      june: 17,
      july: 19,
      august: 19,
      september: 16,
      october: 12,
      november: 8,
      december: 5,
    },
  },
  {
    city: "Istanbul",
    country: "Turkey",
    lat: 41.0082,
    lng: 28.9784,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 6,
      february: 7,
      march: 9,
      april: 13,
      may: 18,
      june: 23,
      july: 26,
      august: 27,
      september: 23,
      october: 18,
      november: 13,
      december: 8,
    },
  },
  {
    city: "Jakarta",
    country: "Indonesia",
    lat: -6.2088,
    lng: 106.8456,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 27,
      march: 28,
      april: 28,
      may: 28,
      june: 27,
      july: 27,
      august: 27,
      september: 28,
      october: 28,
      november: 28,
      december: 27,
    },
  },
  {
    city: "Kuala Lumpur",
    country: "Malaysia",
    lat: 3.139,
    lng: 101.6869,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 28,
      march: 28,
      april: 28,
      may: 28,
      june: 28,
      july: 27,
      august: 27,
      september: 27,
      october: 27,
      november: 27,
      december: 27,
    },
  },
  {
    city: "Lech Am Arlberg",
    country: "Austria",
    lat: 47.2102,
    lng: 10.1427,
    purposes: ["ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: -4,
      february: -3,
      march: 0,
      april: 4,
      may: 8,
      june: 12,
      july: 15,
      august: 15,
      september: 11,
      october: 7,
      november: 1,
      december: -3,
    },
  },
  {
    city: "Oia",
    country: "Greece",
    lat: 36.4618,
    lng: 25.3753,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 12,
      february: 12,
      march: 14,
      april: 17,
      may: 21,
      june: 25,
      july: 27,
      august: 27,
      september: 25,
      october: 21,
      november: 17,
      december: 13,
    },
  },
  {
    city: "Providenciales",
    country: "Turks & Caicos Islands",
    lat: 21.7736,
    lng: -72.2659,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 25,
      february: 25,
      march: 26,
      april: 27,
      may: 28,
      june: 29,
      july: 29,
      august: 29,
      september: 29,
      october: 28,
      november: 27,
      december: 26,
    },
  },
  {
    city: "Sabi Sand Reserve",
    country: "South Africa",
    lat: -24.807,
    lng: 31.385,
    purposes: ["safari"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 24,
      february: 24,
      march: 23,
      april: 21,
      may: 18,
      june: 15,
      july: 15,
      august: 18,
      september: 21,
      october: 23,
      november: 23,
      december: 24,
    },
  },
  {
    city: "Saint Tropez",
    country: "France",
    lat: 43.2676,
    lng: 6.6407,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 9,
      february: 10,
      march: 12,
      april: 14,
      may: 18,
      june: 22,
      july: 25,
      august: 25,
      september: 22,
      october: 18,
      november: 13,
      december: 10,
    },
  },
  {
    city: "Zurich",
    country: "Switzerland",
    lat: 47.3769,
    lng: 8.5417,
    purposes: ["city_break", "ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: 1,
      february: 3,
      march: 7,
      april: 10,
      may: 14,
      june: 18,
      july: 20,
      august: 20,
      september: 16,
      october: 11,
      november: 6,
      december: 2,
    },
  },
  {
    city: "Athens",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 10,
      february: 11,
      march: 13,
      april: 17,
      may: 22,
      june: 27,
      july: 30,
      august: 30,
      september: 26,
      october: 21,
      november: 16,
      december: 12,
    },
  },
  {
    city: "Berlin",
    country: "Germany",
    lat: 52.52,
    lng: 13.405,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 1,
      february: 2,
      march: 5,
      april: 10,
      may: 15,
      june: 19,
      july: 21,
      august: 21,
      september: 16,
      october: 11,
      november: 6,
      december: 2,
    },
  },
  {
    city: "Beverly Hills",
    country: "USA",
    lat: 34.0736,
    lng: -118.4004,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 14,
      february: 15,
      march: 16,
      april: 18,
      may: 19,
      june: 22,
      july: 24,
      august: 24,
      september: 24,
      october: 21,
      november: 17,
      december: 14,
    },
  },
  {
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: -1,
      february: 0,
      march: 4,
      april: 10,
      may: 16,
      june: 21,
      july: 24,
      august: 23,
      september: 19,
      october: 13,
      november: 8,
      december: 2,
    },
  },
  {
    city: "Cabo San Lucas",
    country: "Mexico",
    lat: 22.8905,
    lng: -109.9167,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 21,
      february: 21,
      march: 22,
      april: 24,
      may: 26,
      june: 28,
      july: 30,
      august: 30,
      september: 29,
      october: 28,
      november: 25,
      december: 22,
    },
  },
  {
    city: "Capri",
    country: "Italy",
    lat: 40.5532,
    lng: 14.2222,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 10,
      february: 10,
      march: 12,
      april: 15,
      may: 19,
      june: 23,
      july: 26,
      august: 27,
      september: 24,
      october: 20,
      november: 15,
      december: 11,
    },
  },
  {
    city: "Grumeti Game Reserve",
    country: "Tanzania",
    lat: -2.155,
    lng: 34.685,
    purposes: ["safari"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 23,
      february: 23,
      march: 23,
      april: 22,
      may: 21,
      june: 20,
      july: 20,
      august: 21,
      september: 22,
      october: 23,
      november: 22,
      december: 22,
    },
  },
  {
    city: "Gstaad",
    country: "Switzerland",
    lat: 46.4721,
    lng: 7.2866,
    purposes: ["ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: -4,
      february: -3,
      march: 0,
      april: 4,
      may: 8,
      june: 12,
      july: 15,
      august: 15,
      september: 11,
      october: 7,
      november: 1,
      december: -3,
    },
  },
  {
    city: "Kyoto",
    country: "Japan",
    lat: 35.0116,
    lng: 135.7681,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 5,
      february: 6,
      march: 9,
      april: 15,
      may: 20,
      june: 24,
      july: 28,
      august: 29,
      september: 25,
      october: 18,
      november: 12,
      december: 7,
    },
  },
  {
    city: "Monte Carlo",
    country: "Monaco",
    lat: 43.7384,
    lng: 7.4246,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 9,
      february: 10,
      march: 12,
      april: 14,
      may: 18,
      june: 22,
      july: 25,
      august: 25,
      september: 22,
      october: 18,
      november: 13,
      december: 10,
    },
  },
  {
    city: "Rio de Janeiro",
    country: "Brazil",
    lat: -22.9068,
    lng: -43.1729,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 28,
      march: 27,
      april: 25,
      may: 23,
      june: 22,
      july: 21,
      august: 22,
      september: 23,
      october: 24,
      november: 25,
      december: 26,
    },
  },
  {
    city: "San Jose del Cabo",
    country: "Mexico",
    lat: 23.061,
    lng: -109.7014,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 21,
      february: 21,
      march: 22,
      april: 24,
      may: 26,
      june: 28,
      july: 30,
      august: 30,
      september: 29,
      october: 28,
      november: 25,
      december: 22,
    },
  },
  {
    city: "Taormina",
    country: "Italy",
    lat: 37.8516,
    lng: 15.2853,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 10,
      february: 11,
      march: 13,
      april: 16,
      may: 20,
      june: 24,
      july: 27,
      august: 28,
      september: 25,
      october: 21,
      november: 16,
      december: 12,
    },
  },
  {
    city: "Vienna",
    country: "Austria",
    lat: 48.2082,
    lng: 16.3738,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 1,
      february: 3,
      march: 8,
      april: 13,
      may: 17,
      june: 21,
      july: 24,
      august: 23,
      september: 18,
      october: 12,
      november: 6,
      december: 2,
    },
  },
  {
    city: "Zermatt",
    country: "Switzerland",
    lat: 46.0207,
    lng: 7.7491,
    purposes: ["ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: -6,
      february: -5,
      march: -2,
      april: 2,
      may: 6,
      june: 10,
      july: 13,
      august: 13,
      september: 9,
      october: 4,
      november: -1,
      december: -4,
    },
  },
  {
    city: "Amalfi",
    country: "Italy",
    lat: 40.634,
    lng: 14.6027,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 10,
      february: 10,
      march: 12,
      april: 15,
      may: 19,
      june: 23,
      july: 26,
      august: 27,
      september: 24,
      october: 20,
      november: 15,
      december: 11,
    },
  },
  {
    city: "Arenal",
    country: "Costa Rica",
    lat: 10.4631,
    lng: -84.7036,
    purposes: ["mountains"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 24,
      february: 25,
      march: 26,
      april: 26,
      may: 25,
      june: 24,
      july: 24,
      august: 24,
      september: 24,
      october: 23,
      november: 23,
      december: 24,
    },
  },
  {
    city: "Bath",
    country: "England",
    lat: 51.3811,
    lng: -2.359,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 5,
      february: 6,
      march: 8,
      april: 10,
      may: 13,
      june: 16,
      july: 19,
      august: 18,
      september: 16,
      october: 12,
      november: 8,
      december: 6,
    },
  },
  {
    city: "Bo Phut",
    country: "Thailand",
    lat: 9.5581,
    lng: 100.0221,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 28,
      march: 29,
      april: 30,
      may: 30,
      june: 29,
      july: 29,
      august: 29,
      september: 28,
      october: 28,
      november: 27,
      december: 27,
    },
  },
  {
    city: "Bodrum",
    country: "Turkey",
    lat: 37.0344,
    lng: 27.4305,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 11,
      february: 11,
      march: 13,
      april: 16,
      may: 21,
      june: 26,
      july: 29,
      august: 29,
      september: 25,
      october: 21,
      november: 16,
      december: 12,
    },
  },
  {
    city: "Bora Bora",
    country: "French Polynesia",
    lat: -16.5004,
    lng: -151.7415,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 28,
      february: 28,
      march: 28,
      april: 28,
      may: 27,
      june: 26,
      july: 25,
      august: 25,
      september: 26,
      october: 26,
      november: 27,
      december: 28,
    },
  },
  {
    city: "Budapest",
    country: "Hungary",
    lat: 47.4979,
    lng: 19.0402,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 0,
      february: 3,
      march: 8,
      april: 13,
      may: 18,
      june: 22,
      july: 24,
      august: 24,
      september: 19,
      october: 13,
      november: 7,
      december: 2,
    },
  },
  {
    city: "Buenos Aires",
    country: "Argentina",
    lat: -34.6037,
    lng: -58.3816,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 25,
      february: 24,
      march: 22,
      april: 18,
      may: 15,
      june: 12,
      july: 11,
      august: 13,
      september: 15,
      october: 18,
      november: 21,
      december: 24,
    },
  },
  {
    city: "Cairo",
    country: "Egypt",
    lat: 30.0444,
    lng: 31.2357,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 14,
      february: 16,
      march: 18,
      april: 22,
      may: 26,
      june: 29,
      july: 30,
      august: 30,
      september: 28,
      october: 25,
      november: 20,
      december: 16,
    },
  },
  {
    city: "Chiang Rai",
    country: "Thailand",
    lat: 19.9105,
    lng: 99.8406,
    purposes: ["mountains"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 21,
      february: 24,
      march: 27,
      april: 29,
      may: 28,
      june: 27,
      july: 27,
      august: 27,
      september: 26,
      october: 25,
      november: 23,
      december: 20,
    },
  },
  {
    city: "Cologne",
    country: "Germany",
    lat: 50.9375,
    lng: 6.9603,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 4,
      february: 5,
      march: 8,
      april: 11,
      may: 15,
      june: 18,
      july: 20,
      august: 20,
      september: 17,
      october: 12,
      november: 8,
      december: 5,
    },
  },
  {
    city: "Copenhagen",
    country: "Denmark",
    lat: 55.6761,
    lng: 12.5683,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 1,
      february: 1,
      march: 4,
      april: 8,
      may: 13,
      june: 17,
      july: 19,
      august: 19,
      september: 15,
      october: 11,
      november: 6,
      december: 3,
    },
  },
  {
    city: "Crans-Montana",
    country: "Switzerland",
    lat: 46.3099,
    lng: 7.4789,
    purposes: ["ski", "mountains"],
    coastal: false,
    ski: true,
    monthlyAvgTempC: {
      january: -4,
      february: -3,
      march: 0,
      april: 4,
      may: 8,
      june: 12,
      july: 15,
      august: 14,
      september: 11,
      october: 7,
      november: 1,
      december: -3,
    },
  },
  {
    city: "Dallas",
    country: "USA",
    lat: 32.7767,
    lng: -96.797,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 9,
      february: 11,
      march: 15,
      april: 19,
      may: 24,
      june: 28,
      july: 31,
      august: 31,
      september: 27,
      october: 21,
      november: 15,
      december: 10,
    },
  },
  {
    city: "Dana Point",
    country: "USA",
    lat: 33.4669,
    lng: -117.6981,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 14,
      february: 15,
      march: 16,
      april: 17,
      may: 18,
      june: 20,
      july: 22,
      august: 23,
      september: 23,
      october: 21,
      november: 18,
      december: 14,
    },
  },
  {
    city: "Djimbaran",
    country: "Indonesia",
    lat: -8.7902,
    lng: 115.1606,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 27,
      march: 27,
      april: 28,
      may: 28,
      june: 27,
      july: 26,
      august: 26,
      september: 27,
      october: 28,
      november: 28,
      december: 27,
    },
  },
  {
    city: "Fari Islands",
    country: "Maldives",
    lat: 4.3103,
    lng: 73.4259,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 28,
      march: 29,
      april: 30,
      may: 30,
      june: 29,
      july: 29,
      august: 29,
      september: 29,
      october: 28,
      november: 28,
      december: 27,
    },
  },
  {
    city: "Hamburg",
    country: "Germany",
    lat: 53.5511,
    lng: 9.9937,
    purposes: ["city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 2,
      february: 3,
      march: 6,
      april: 10,
      may: 14,
      june: 17,
      july: 19,
      august: 19,
      september: 15,
      october: 11,
      november: 6,
      december: 3,
    },
  },
  {
    city: "Ho Chi Minh City",
    country: "Vietnam",
    lat: 10.8231,
    lng: 106.6297,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 26,
      february: 27,
      march: 28,
      april: 29,
      may: 29,
      june: 28,
      july: 28,
      august: 28,
      september: 27,
      october: 27,
      november: 27,
      december: 26,
    },
  },
  {
    city: "Lausanne",
    country: "Switzerland",
    lat: 46.5197,
    lng: 6.6323,
    purposes: ["city_break", "mountains"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 2,
      february: 4,
      march: 8,
      april: 11,
      may: 16,
      june: 20,
      july: 23,
      august: 22,
      september: 18,
      october: 13,
      november: 7,
      december: 3,
    },
  },
  {
    city: "Los Angeles",
    country: "USA",
    lat: 34.0522,
    lng: -118.2437,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 14,
      february: 15,
      march: 16,
      april: 18,
      may: 19,
      june: 22,
      july: 24,
      august: 24,
      september: 24,
      october: 21,
      november: 17,
      december: 14,
    },
  },
  {
    city: "Los Cabos",
    country: "Mexico",
    lat: 23.4167,
    lng: -109.4333,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 21,
      february: 21,
      march: 22,
      april: 24,
      may: 26,
      june: 28,
      july: 30,
      august: 30,
      september: 29,
      october: 28,
      november: 25,
      december: 22,
    },
  },
  {
    city: "Lucerne",
    country: "Switzerland",
    lat: 47.0502,
    lng: 8.3093,
    purposes: ["city_break", "mountains"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: 1,
      february: 3,
      march: 7,
      april: 11,
      may: 15,
      june: 19,
      july: 21,
      august: 20,
      september: 17,
      october: 12,
      november: 6,
      december: 2,
    },
  },
  {
    city: "Macau",
    country: "China",
    lat: 22.1987,
    lng: 113.5439,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 16,
      february: 17,
      march: 20,
      april: 24,
      may: 27,
      june: 29,
      july: 30,
      august: 29,
      september: 28,
      october: 25,
      november: 22,
      december: 18,
    },
  },
  {
    city: "Manila",
    country: "Philippines",
    lat: 14.5995,
    lng: 120.9842,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 26,
      february: 27,
      march: 28,
      april: 30,
      may: 30,
      june: 29,
      july: 28,
      august: 28,
      september: 28,
      october: 28,
      november: 27,
      december: 26,
    },
  },
  {
    city: "Marbella",
    country: "Spain",
    lat: 36.5102,
    lng: -4.8825,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 12,
      february: 13,
      march: 15,
      april: 17,
      may: 20,
      june: 24,
      july: 27,
      august: 27,
      september: 24,
      october: 20,
      november: 16,
      december: 13,
    },
  },
  {
    city: "Miami",
    country: "USA",
    lat: 25.7617,
    lng: -80.1918,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 20,
      february: 21,
      march: 23,
      april: 25,
      may: 27,
      june: 29,
      july: 30,
      august: 30,
      september: 29,
      october: 27,
      november: 24,
      december: 21,
    },
  },
  {
    city: "Moscow",
    country: "Russia",
    lat: 55.7558,
    lng: 37.6173,
    purposes: ["city_break"],
    coastal: false,
    ski: false,
    monthlyAvgTempC: {
      january: -8,
      february: -7,
      march: -2,
      april: 6,
      may: 13,
      june: 17,
      july: 19,
      august: 17,
      september: 11,
      october: 5,
      november: -1,
      december: -6,
    },
  },
  {
    city: "Mumbai",
    country: "India",
    lat: 19.076,
    lng: 72.8777,
    purposes: ["city_break", "beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 24,
      february: 25,
      march: 27,
      april: 29,
      may: 30,
      june: 29,
      july: 27,
      august: 27,
      september: 28,
      october: 29,
      november: 28,
      december: 26,
    },
  },
  {
    city: "Mykonos Town",
    country: "Greece",
    lat: 37.4467,
    lng: 25.3289,
    purposes: ["beach", "city_break"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 12,
      february: 12,
      march: 13,
      april: 16,
      may: 20,
      june: 24,
      july: 27,
      august: 27,
      september: 24,
      october: 21,
      november: 17,
      december: 14,
    },
  },
  {
    city: "Nusa Dua",
    country: "Indonesia",
    lat: -8.8093,
    lng: 115.2244,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 27,
      february: 27,
      march: 27,
      april: 28,
      may: 28,
      june: 27,
      july: 26,
      august: 26,
      september: 27,
      october: 28,
      november: 28,
      december: 27,
    },
  },
  {
    city: "Ornos",
    country: "Greece",
    lat: 37.4221,
    lng: 25.3223,
    purposes: ["beach"],
    coastal: true,
    ski: false,
    monthlyAvgTempC: {
      january: 12,
      february: 12,
      march: 13,
      april: 16,
      may: 20,
      june: 24,
      july: 27,
      august: 27,
      september: 24,
      october: 21,
      november: 17,
      december: 14,
    },
  },
];