import type { InspireCity } from "./types";

export const MOCK_INSPIRE_CITIES: InspireCity[] = [
  {
    id: "lisbon",
    city: "Lisbon",
    country: "Portugal",
    region: "Southern Europe",
    lat: 38.7223,
    lng: -9.1393,
    hotelCount: 18,
    purposes: ["city_break", "beach"],
    monthlyAvgTempC: {
      january: 11,
      february: 12,
      march: 14,
      april: 16,
      may: 19,
      june: 22,
      july: 25,
      august: 26,
      september: 24,
      october: 20,
      november: 15,
      december: 12,
    },
  },
  {
    id: "dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    lat: 25.2048,
    lng: 55.2708,
    hotelCount: 22,
    purposes: ["beach", "city_break"],
    monthlyAvgTempC: {
      january: 19,
      february: 20,
      march: 23,
      april: 27,
      may: 31,
      june: 33,
      july: 35,
      august: 35,
      september: 33,
      october: 30,
      november: 25,
      december: 21,
    },
  },
  {
    id: "marrakech",
    city: "Marrakech",
    country: "Morocco",
    region: "North Africa",
    lat: 31.6295,
    lng: -7.9811,
    hotelCount: 12,
    purposes: ["city_break", "mountains"],
    monthlyAvgTempC: {
      january: 12,
      february: 14,
      march: 17,
      april: 19,
      may: 23,
      june: 27,
      july: 31,
      august: 31,
      september: 27,
      october: 22,
      november: 17,
      december: 13,
    },
  },
  {
    id: "male",
    city: "Malé",
    country: "Maldives",
    region: "Indian Ocean",
    lat: 4.1755,
    lng: 73.5093,
    hotelCount: 14,
    purposes: ["beach"],
    monthlyAvgTempC: {
      january: 27,
      february: 28,
      march: 29,
      april: 30,
      may: 30,
      june: 29,
      july: 29,
      august: 29,
      september: 29,
      october: 28,
      november: 28,
      december: 27,
    },
  },
  {
    id: "geneva",
    city: "Geneva",
    country: "Switzerland",
    region: "Central Europe",
    lat: 46.2044,
    lng: 6.1432,
    hotelCount: 9,
    purposes: ["ski", "city_break", "mountains"],
    monthlyAvgTempC: {
      january: 2,
      february: 4,
      march: 8,
      april: 11,
      may: 16,
      june: 20,
      july: 23,
      august: 22,
      september: 18,
      october: 13,
      november: 7,
      december: 3,
    },
  },
  {
    id: "cape-town",
    city: "Cape Town",
    country: "South Africa",
    region: "Southern Africa",
    lat: -33.9249,
    lng: 18.4241,
    hotelCount: 16,
    purposes: ["beach", "city_break", "mountains", "safari"],
    monthlyAvgTempC: {
      january: 22,
      february: 22,
      march: 21,
      april: 18,
      may: 16,
      june: 13,
      july: 13,
      august: 14,
      september: 15,
      october: 17,
      november: 19,
      december: 21,
    },
  },
  {
    id: "nairobi",
    city: "Nairobi",
    country: "Kenya",
    region: "East Africa",
    lat: -1.2921,
    lng: 36.8219,
    hotelCount: 10,
    purposes: ["safari", "city_break"],
    monthlyAvgTempC: {
      january: 20,
      february: 21,
      march: 21,
      april: 20,
      may: 18,
      june: 17,
      july: 16,
      august: 17,
      september: 19,
      october: 20,
      november: 19,
      december: 20,
    },
  },
];