// AUTO-GENERATED by scripts/airports/build-city-airports.mjs — do not
// hand-edit. Re-run that script to regenerate. See its header comment and
// CLAUDE.md for the nearest-airport selection rule and known limitations.

export type CityAirport = {
  iata: string;
  label: string;
  distKm: number;
};

export const CITY_AIRPORTS: Record<string, CityAirport[]> = {
  "Abu Dhabi": [
    { iata: "AUH", label: "Zayed", distKm: 32 }
  ],
  "Acapulco": [
    { iata: "ACA", label: "General Juan N. Álvarez", distKm: 12 }
  ],
  "Adare": [
    { iata: "SNN", label: "Shannon", distKm: 18 }
  ],
  "Agios Ioannis": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 4 }
  ],
  "Agra": [
    { iata: "AGR", label: "Agra / Agra Air Force Station", distKm: 9 }
  ],
  "Akrotiri": [
    { iata: "ZTH", label: "Zakynthos Dionysios Solomos", distKm: 7 }
  ],
  "Al Wajh": [
    { iata: "RSI", label: "Red Sea", distKm: 18 }
  ],
  "Aleomandra": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 4 }
  ],
  "Alpe de Siusi": [
    { iata: "BZO", label: "Bolzano", distKm: 24 }
  ],
  "Alta Badia": [
    { iata: "BZO", label: "Bolzano", distKm: 48 }
  ],
  "Alto Agrelo": [
    { iata: "MDZ", label: "Governor Francisco Gabrielli", distKm: 34 }
  ],
  "Alula": [
    { iata: "ULH", label: "Al-Ula", distKm: 40 }
  ],
  "Amalfi": [
    { iata: "QSR", label: "Salerno Costa d'Amalfi", distKm: 28 },
    { iata: "NAP", label: "Naples", distKm: 38 }
  ],
  "Amphur Muang": [
    { iata: "KBV", label: "Krabi", distKm: 19 }
  ],
  "Amsterdam": [
    { iata: "AMS", label: "Amsterdam Schiphol", distKm: 10 }
  ],
  "Anacapri": [
    { iata: "NAP", label: "Naples", distKm: 37 }
  ],
  "Analipsis Hersonissos": [
    { iata: "HER", label: "Heraklion Nikos Kazantzakis", distKm: 14 }
  ],
  "Andermatt": [
    { iata: "LUG", label: "Lugano", distKm: 74 },
    { iata: "BRN", label: "Bern", distKm: 89 }
  ],
  "Angthong": [
    { iata: "USM", label: "Samui", distKm: 15 }
  ],
  "Anse Aux Poules Bleues": [
    { iata: "SEZ", label: "Seychelles", distKm: 9 }
  ],
  "Anse Boileau": [
    { iata: "SEZ", label: "Seychelles", distKm: 7 }
  ],
  "Anse Intendance": [
    { iata: "SEZ", label: "Seychelles", distKm: 12 }
  ],
  "Anse Kerlan": [
    { iata: "PRI", label: "Praslin Island", distKm: 3 }
  ],
  "Antibes": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 14 }
  ],
  "Arenal": [
    { iata: "FON", label: "La Fortuna Arenal", distKm: 13 }
  ],
  "Argolida": [
    { iata: "ATH", label: "Athens Eleftherios Venizelos", distKm: 96 },
    { iata: "KLX", label: "Kalamata", distKm: 102 }
  ],
  "Arosa": [
    { iata: "ACH", label: "Sankt Gallen Altenrhein", distKm: 79 },
    { iata: "FDH", label: "Bodensee Friedrichshafen", distKm: 100 }
  ],
  "Arue Tahiti": [
    { iata: "MOZ", label: "Moorea Temae", distKm: 55 },
    { iata: "PPT", label: "Fa'a'ā", distKm: 59 }
  ],
  "Ashar Valley": [
    { iata: "ULH", label: "Al-Ula", distKm: 39 }
  ],
  "Asni": [
    { iata: "RAK", label: "Marrakesh Menara", distKm: 43 }
  ],
  "Aspen": [
    { iata: "ASE", label: "Aspen-Pitkin County", distKm: 6 }
  ],
  "Athens": [
    { iata: "ATH", label: "Athens Eleftherios Venizelos", distKm: 19 }
  ],
  "Atlanta": [
    { iata: "PDK", label: "DeKalb Peachtree", distKm: 6 },
    { iata: "ATL", label: "Hartsfield Jackson Atlanta", distKm: 25 }
  ],
  "Avon": [
    { iata: "EGE", label: "Eagle County", distKm: 32 }
  ],
  "Ayios Yiannis": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 3 }
  ],
  "Bad Ragaz": [
    { iata: "ACH", label: "Sankt Gallen Altenrhein", distKm: 54 },
    { iata: "FDH", label: "Bodensee Friedrichshafen", distKm: 75 }
  ],
  "Baden-Baden": [
    { iata: "FKB", label: "Karlsruhe Baden-Baden", distKm: 12 }
  ],
  "Bai Truong": [
    { iata: "PQC", label: "Phú Quốc", distKm: 7 }
  ],
  "Baku": [
    { iata: "GYD", label: "Heydar Aliyev", distKm: 22 }
  ],
  "Ballyfin": [
    { iata: "DUB", label: "Dublin", distKm: 87 },
    { iata: "SNN", label: "Shannon", distKm: 109 }
  ],
  "Banff": [
    { iata: "YYC", label: "Calgary", distKm: 108 }
  ],
  "Bangkok": [
    { iata: "DMK", label: "Don Mueang", distKm: 22 },
    { iata: "BKK", label: "Suvarnabhumi", distKm: 24 }
  ],
  "Banjar Dinas Kangin Uluwatu": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 12 }
  ],
  "Banjar Dukuh": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 23 }
  ],
  "Banjar Triwangsa": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 35 }
  ],
  "Banyalbufar": [
    { iata: "PMI", label: "Palma de Mallorca", distKm: 23 }
  ],
  "Barcelona": [
    { iata: "BCN", label: "Josep Tarradellas Barcelona-El Prat", distKm: 13 }
  ],
  "Barnard": [
    { iata: "LEB", label: "Lebanon", distKm: 26 },
    { iata: "RUT", label: "Rutland - Southern Vermont", distKm: 36 }
  ],
  "Basel": [
    { iata: "BSL", label: "EuroAirport Basel-Mulhouse-Freiburg", distKm: 7 }
  ],
  "Bath": [
    { iata: "BRS", label: "Bristol", distKm: 28 }
  ],
  "Beaulieu-Sur-Mer": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 11 }
  ],
  "Beaver Creek": [
    { iata: "EGE", label: "Eagle County", distKm: 35 }
  ],
  "Beijing": [
    { iata: "PEK", label: "Beijing Capital", distKm: 22 },
    { iata: "PKX", label: "Beijing Daxing", distKm: 47 }
  ],
  "Belgrade": [
    { iata: "BEG", label: "Belgrade Nikola Tesla", distKm: 12 }
  ],
  "Belle Mare": [
    { iata: "MRU", label: "Sir Seewoosagur Ramgoolam", distKm: 28 }
  ],
  "Benguerra Island": [
    { iata: "VNX", label: "Vilankulo", distKm: 18 }
  ],
  "Berlin": [
    { iata: "BER", label: "Berlin Brandenburg", distKm: 19 }
  ],
  "Beverly Hills": [
    { iata: "LAX", label: "Los Angeles", distKm: 14 },
    { iata: "BUR", label: "Hollywood Burbank/Bob Hope", distKm: 15 },
    { iata: "HHR", label: "Jack Northrop Field Hawthorne", distKm: 18 }
  ],
  "Biarritz": [
    { iata: "BIQ", label: "Biarritz Pays Basque", distKm: 3 },
    { iata: "EAS", label: "San Sebastián", distKm: 24 }
  ],
  "Big Island": [
    { iata: "MUE", label: "Waimea Kohala", distKm: 22 }
  ],
  "Big Island, Ka`Upulehu-Kona HI": [
    { iata: "KOA", label: "Ellison Onizuka Kona at Keāhole", distKm: 11 }
  ],
  "Big Sky": [
    { iata: "BZN", label: "Bozeman Yellowstone", distKm: 60 },
    { iata: "WYS", label: "Yellowstone", distKm: 66 }
  ],
  "Big Sur": [
    { iata: "MRY", label: "Monterey", distKm: 40 }
  ],
  "Blevio": [
    { iata: "LUG", label: "Lugano", distKm: 23 }
  ],
  "Blois": [
    { iata: "TUF", label: "Tours Val de Loire", distKm: 49 }
  ],
  "Bo Phut": [
    { iata: "USM", label: "Samui", distKm: 4 }
  ],
  "Boca Raton": [
    { iata: "FLL", label: "Fort Lauderdale Hollywood", distKm: 31 },
    { iata: "PBI", label: "President Donald J. Trump", distKm: 38 }
  ],
  "Bodrum": [
    { iata: "BJV", label: "Milas Bodrum", distKm: 30 }
  ],
  "Bora Bora": [
    { iata: "BOB", label: "Bora Bora", distKm: 7 }
  ],
  "Borobudur": [
    { iata: "JOG", label: "Adisutjipto", distKm: 31 },
    { iata: "YIA", label: "Yogyakarta", distKm: 34 }
  ],
  "Boston": [
    { iata: "BOS", label: "Boston Logan", distKm: 5 },
    { iata: "BED", label: "Laurence G Hanscom Field", distKm: 22 }
  ],
  "Brixen": [
    { iata: "BZO", label: "Bolzano", distKm: 38 }
  ],
  "Buahan": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 43 }
  ],
  "Budapest": [
    { iata: "BUD", label: "Budapest Liszt Ferenc", distKm: 18 }
  ],
  "Buenos Aires": [
    { iata: "AEP", label: "Aeroparque Jorge Newbery", distKm: 6 },
    { iata: "EZE", label: "Ezeiza - Ministro Pistarini", distKm: 29 }
  ],
  "Bukit Peninsula": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 11 }
  ],
  "By Achnasheen": [
    { iata: "INV", label: "Inverness", distKm: 88 },
    { iata: "SYY", label: "Stornoway", distKm: 90 }
  ],
  "Cabo San Lucas": [
    { iata: "CSW", label: "Cabo San Lucas", distKm: 7 }
  ],
  "Cairo": [
    { iata: "CAI", label: "Cairo", distKm: 19 }
  ],
  "Cala Blava-Llucmajor": [
    { iata: "PMI", label: "Palma de Mallorca", distKm: 8 }
  ],
  "Calistoga": [
    { iata: "STS", label: "Charles M. Schulz Sonoma County", distKm: 23 }
  ],
  "Calvia": [
    { iata: "PMI", label: "Palma de Mallorca", distKm: 23 }
  ],
  "Cancun": [
    { iata: "CUN", label: "Cancún", distKm: 9 }
  ],
  "Cannes": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 20 }
  ],
  "Canouan Island": [
    { iata: "CIW", label: "Canouan", distKm: 3 },
    { iata: "UNI", label: "Union Island", distKm: 17 },
    { iata: "MQS", label: "Mustique", distKm: 24 }
  ],
  "Canyon Point": [
    { iata: "PGA", label: "Page", distKm: 18 }
  ],
  "Cap Ferrat": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 10 }
  ],
  "Cape Panwa": [
    { iata: "HKT", label: "Phuket", distKm: 36 }
  ],
  "Cape Town": [
    { iata: "CPT", label: "Cape Town", distKm: 19 }
  ],
  "Capri": [
    { iata: "NAP", label: "Naples", distKm: 38 }
  ],
  "Carenage Bay": [
    { iata: "CIW", label: "Canouan", distKm: 3 },
    { iata: "UNI", label: "Union Island", distKm: 16 },
    { iata: "MQS", label: "Mustique", distKm: 25 }
  ],
  "Carmel Valley": [
    { iata: "MRY", label: "Monterey", distKm: 13 }
  ],
  "Carretera": [
    { iata: "CZM", label: "Cozumel", distKm: 34 }
  ],
  "Cary": [
    { iata: "RDU", label: "Raleigh-Durham", distKm: 6 }
  ],
  "Casares": [
    { iata: "GIB", label: "Gibraltar", distKm: 30 }
  ],
  "Casole d'Elsa": [
    { iata: "FLR", label: "Florence, Peretola", distKm: 55 },
    { iata: "PSA", label: "Pisa", distKm: 69 }
  ],
  "Cernobbio": [
    { iata: "LUG", label: "Lugano", distKm: 22 }
  ],
  "Cerretto Langhe": [
    { iata: "CUF", label: "Cuneo", distKm: 34 }
  ],
  "Cervinia": [
    { iata: "TRN", label: "Turin", distKm: 81 },
    { iata: "MXP", label: "Milan Malpensa", distKm: 92 }
  ],
  "Chamonix": [
    { iata: "NCY", label: "Annecy Meythet", distKm: 60 },
    { iata: "GVA", label: "Geneva", distKm: 69 }
  ],
  "Chania": [
    { iata: "CHQ", label: "Chania", distKm: 14 }
  ],
  "Chatham": [
    { iata: "HYA", label: "Cape Cod Gateway", distKm: 24 }
  ],
  "Chauth Ka Barwara": [
    { iata: "JAI", label: "Jaipur", distKm: 93 }
  ],
  "Chengdu": [
    { iata: "CTU", label: "Chengdu Shuangliu", distKm: 17 },
    { iata: "TFU", label: "Chengdu Tianfu", distKm: 51 }
  ],
  "Cherngtalay": [
    { iata: "HKT", label: "Phuket", distKm: 10 }
  ],
  "Chiang Mai": [
    { iata: "CNX", label: "Chiang Mai", distKm: 17 }
  ],
  "Chiang Rai": [
    { iata: "BOR", label: "Bokeo", distKm: 11 },
    { iata: "THL", label: "Tachileik", distKm: 19 },
    { iata: "CEI", label: "Mae Fah Luang - Chiang Rai", distKm: 51 }
  ],
  "Chicago": [
    { iata: "MDW", label: "Chicago Midway", distKm: 16 },
    { iata: "ORD", label: "Chicago O'Hare", distKm: 25 }
  ],
  "Chobe National Park": [
    { iata: "MPA", label: "Katima Mulilo", distKm: 105 },
    { iata: "BBK", label: "Kasane", distKm: 143 }
  ],
  "Chochola": [
    { iata: "MID", label: "Manuel Crescencio Rejón", distKm: 30 }
  ],
  "Chongzou": [
    { iata: "AEB", label: "Baise Bama", distKm: 114 },
    { iata: "NNG", label: "Nanning Wuxu", distKm: 129 }
  ],
  "Cocoa Island": [
    { iata: "MLE", label: "Velana", distKm: 31 }
  ],
  "Cognac": [
    { iata: "LRH", label: "La Rochelle Île de Ré", distKm: 86 },
    { iata: "BOD", label: "Bordeaux-Mérignac", distKm: 100 }
  ],
  "Cologne": [
    { iata: "CGN", label: "Cologne Bonn", distKm: 11 }
  ],
  "Colorado Springs": [
    { iata: "COS", label: "City of Colorado Springs", distKm: 13 }
  ],
  "Con Dao Town": [
    { iata: "VCS", label: "Con Dao", distKm: 3 }
  ],
  "Cong": [
    { iata: "NNR", label: "Connemara", distKm: 36 },
    { iata: "NOC", label: "Ireland West Knock", distKm: 52 }
  ],
  "Copenhagen": [
    { iata: "CPH", label: "Copenhagen Kastrup", distKm: 8 },
    { iata: "RKE", label: "Copenhagen Roskilde", distKm: 30 }
  ],
  "Corfu": [
    { iata: "CFU", label: "Corfu Ioannis Kapodistrias", distKm: 11 }
  ],
  "Costa Smeralda": [
    { iata: "OLB", label: "Olbia Costa Smeralda", distKm: 23 }
  ],
  "Courchevel": [
    { iata: "CMF", label: "Chambéry Aix les Bains", distKm: 64 },
    { iata: "NCY", label: "Annecy Meythet", distKm: 71 }
  ],
  "Courchevel 1850": [
    { iata: "CMF", label: "Chambéry Aix les Bains", distKm: 64 },
    { iata: "NCY", label: "Annecy Meythet", distKm: 71 }
  ],
  "Crans-Montana": [
    { iata: "BRN", label: "Bern", distKm: 67 }
  ],
  "Cusco": [
    { iata: "CUZ", label: "Alejandro Velasco Astete", distKm: 5 }
  ],
  "Da Nang": [
    { iata: "DAD", label: "Da Nang", distKm: 14 }
  ],
  "Dallas": [
    { iata: "DAL", label: "Dallas Love Field", distKm: 4 },
    { iata: "DFW", label: "Dallas Fort Worth", distKm: 17 }
  ],
  "Dana Point": [
    { iata: "SNA", label: "John Wayne Orange County", distKm: 26 }
  ],
  "Deauville": [
    { iata: "DOL", label: "Deauville Normandie", distKm: 6 }
  ],
  "Deia": [
    { iata: "PMI", label: "Palma de Mallorca", distKm: 23 }
  ],
  "Den Haag": [
    { iata: "RTM", label: "Rotterdam The Hague", distKm: 16 }
  ],
  "Desroches Island": [
    { iata: "SEZ", label: "Seychelles", distKm: 236 },
    { iata: "PRI", label: "Praslin Island", distKm: 273 }
  ],
  "Dibba": [
    { iata: "RKT", label: "Ras Al Khaimah", distKm: 34 }
  ],
  "Djimbaran": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 5 }
  ],
  "Doha": [
    { iata: "DIA", label: "Doha", distKm: 6 },
    { iata: "DOH", label: "Hamad", distKm: 8 }
  ],
  "Dorado": [
    { iata: "SIG", label: "Fernando Luis Ribas Dominicci", distKm: 21 }
  ],
  "Dubai": [
    { iata: "DXB", label: "Dubai", distKm: 12 },
    { iata: "DWC", label: "Al Maktoum", distKm: 35 }
  ],
  "Dublin": [
    { iata: "DUB", label: "Dublin", distKm: 9 }
  ],
  "Dubrovnik": [
    { iata: "DBV", label: "Dubrovnik Ruđer Bošković", distKm: 14 }
  ],
  "Edinburgh": [
    { iata: "EDI", label: "Edinburgh", distKm: 11 }
  ],
  "Elia Beach": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 4 }
  ],
  "Elmau": [
    { iata: "INN", label: "Innsbruck", distKm: 25 }
  ],
  "Elounda": [
    { iata: "JSH", label: "Sitia", distKm: 34 }
  ],
  "Es Canar": [
    { iata: "IBZ", label: "Ibiza", distKm: 23 }
  ],
  "Eurgenie les Bains": [
    { iata: "PUF", label: "Pau Pyrénées", distKm: 35 }
  ],
  "Eynsham Park": [
    { iata: "LTN", label: "London Luton", distKm: 73 },
    { iata: "BHX", label: "Birmingham", distKm: 75 }
  ],
  "Eze": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 14 }
  ],
  "Èze Bord-De-Mer": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 14 }
  ],
  "Fari Islands Archipelago": [
    { iata: "MLE", label: "Velana", distKm: 47 }
  ],
  "Fasmendhoo Island": [
    { iata: "DRV", label: "Dharavandhoo", distKm: 47 }
  ],
  "Felicite Island": [
    { iata: "PRI", label: "Praslin Island", distKm: 20 }
  ],
  "Fergus": [
    { iata: "SNN", label: "Shannon", distKm: 9 }
  ],
  "Fisher Island": [
    { iata: "MIA", label: "Miami", distKm: 16 },
    { iata: "OPF", label: "Miami-Opa Locka Executive", distKm: 21 }
  ],
  "Fiuggi": [
    { iata: "CIA", label: "Ciampino-G. B. Pastine", distKm: 52 }
  ],
  "Florence": [
    { iata: "FLR", label: "Florence, Peretola", distKm: 6 }
  ],
  "Fort Lauderdale": [
    { iata: "FLL", label: "Fort Lauderdale Hollywood", distKm: 7 }
  ],
  "Fort William": [
    { iata: "OBN", label: "Oban", distKm: 47 }
  ],
  "Forte dei Marmi": [
    { iata: "PSA", label: "Pisa", distKm: 34 }
  ],
  "Funchal": [
    { iata: "FNC", label: "Cristiano Ronaldo", distKm: 15 }
  ],
  "Galapagos": [
    { iata: "GPS", label: "Seymour Galapagos Ecological", distKm: 26 }
  ],
  "Gardone Riviera": [
    { iata: "VBS", label: "Brescia Gabriele d'Annunzio", distKm: 29 },
    { iata: "VRN", label: "Verona Villafranca Valerio Catullo", distKm: 35 }
  ],
  "Gargnano": [
    { iata: "VRN", label: "Verona Villafranca Valerio Catullo", distKm: 37 },
    { iata: "VBS", label: "Brescia Gabriele d'Annunzio", distKm: 40 }
  ],
  "Geneva": [
    { iata: "GVA", label: "Geneva", distKm: 4 }
  ],
  "Gisakura": [
    { iata: "KME", label: "Kamembe", distKm: 22 }
  ],
  "Gordes": [
    { iata: "AVN", label: "Avignon Caumont", distKm: 24 }
  ],
  "Gournes": [
    { iata: "HER", label: "Heraklion Nikos Kazantzakis", distKm: 13 }
  ],
  "Grand Anse Beach": [
    { iata: "GND", label: "Maurice Bishop", distKm: 5 }
  ],
  "Grand Baie": [
    { iata: "MRU", label: "Sir Seewoosagur Ramgoolam", distKm: 48 }
  ],
  "Grand Cul-de-sac": [
    { iata: "SBH", label: "St. Jean", distKm: 4 }
  ],
  "Greenough": [
    { iata: "MSO", label: "Missoula Montana", distKm: 50 }
  ],
  "Greensboro": [
    { iata: "MCN", label: "Middle Georgia", distKm: 93 },
    { iata: "PDK", label: "DeKalb Peachtree", distKm: 113 }
  ],
  "Grumeti Game Reserve": [
    { iata: "SEU", label: "Seronera", distKm: 73 },
    { iata: "MUZ", label: "Musoma", distKm: 82 }
  ],
  "Gstaad": [
    { iata: "BRN", label: "Bern", distKm: 51 }
  ],
  "Guanacaste": [
    { iata: "LIR", label: "Daniel Oduber Quirós", distKm: 16 }
  ],
  "Guangzhou": [
    { iata: "CAN", label: "Guangzhou Baiyun", distKm: 30 }
  ],
  "Gustavia": [
    { iata: "SBH", label: "St. Jean", distKm: 1 }
  ],
  "Haeundae-gu": [
    { iata: "PUS", label: "Gimhae", distKm: 21 }
  ],
  "Hainan Island": [
    { iata: "SYX", label: "Sanya Phoenix", distKm: 36 }
  ],
  "Hamburg": [
    { iata: "HAM", label: "Hamburg Helmut Schmidt", distKm: 8 }
  ],
  "Hampshire": [
    { iata: "LHR", label: "London Heathrow", distKm: 38 },
    { iata: "SOU", label: "Southampton", distKm: 47 }
  ],
  "Hangzhou": [
    { iata: "HGH", label: "Hangzhou Xiaoshan", distKm: 29 }
  ],
  "Hanoi": [
    { iata: "HAN", label: "Noi Bai", distKm: 22 }
  ],
  "Hermanus": [
    { iata: "CPT", label: "Cape Town", distKm: 79 }
  ],
  "Higuera Blanca": [
    { iata: "PVR", label: "Puerto Vallarta", distKm: 28 }
  ],
  "Ho Chi Minh City": [
    { iata: "SGN", label: "Tan Son Nhat", distKm: 7 }
  ],
  "Hoa Thanh": [
    { iata: "UIH", label: "Phu Cat", distKm: 51 },
    { iata: "TBB", label: "Dong Tac", distKm: 56 }
  ],
  "Hoedspruit": [
    { iata: "HDS", label: "Eastgate / Air Force Base Hoedspruit", distKm: 21 }
  ],
  "Hoi An": [
    { iata: "DAD", label: "Da Nang", distKm: 18 }
  ],
  "Hokkaido": [
    { iata: "OKD", label: "Sapporo Okadama", distKm: 77 },
    { iata: "CTS", label: "New Chitose", distKm: 79 }
  ],
  "Honegg": [
    { iata: "ZRH", label: "Zürich", distKm: 53 },
    { iata: "BRN", label: "Bern", distKm: 69 }
  ],
  "Hong Kong": [
    { iata: "HKG", label: "Hong Kong", distKm: 26 }
  ],
  "Honolulu": [
    { iata: "HNL", label: "Daniel K. Inouye", distKm: 11 }
  ],
  "Houston": [
    { iata: "HOU", label: "William P. Hobby", distKm: 21 },
    { iata: "IAH", label: "George Bush Intercontinental", distKm: 28 }
  ],
  "Hua Hin": [
    { iata: "HHQ", label: "Hua Hin", distKm: 11 }
  ],
  "Hudson Valley": [
    { iata: "SWF", label: "New York Stewart", distKm: 21 }
  ],
  "Hurawalhi Island": [
    { iata: "NMF", label: "Maafaru", distKm: 33 }
  ],
  "Huvafen Fushi Island": [
    { iata: "MLE", label: "Velana", distKm: 26 }
  ],
  "Iguazu National Park": [
    { iata: "IGR", label: "Cataratas Del Iguazú", distKm: 7 },
    { iata: "IGU", label: "Cataratas", distKm: 11 }
  ],
  "Imerovigli": [
    { iata: "JTR", label: "Santorini", distKm: 7 }
  ],
  "Inakara Road": [
    { iata: "MRE", label: "Mara Serena Lodge Airstrip", distKm: 65 }
  ],
  "Interlaken": [
    { iata: "BRN", label: "Bern", distKm: 37 }
  ],
  "Ise-Shima": [
    { iata: "NGO", label: "Chubu Centrair", distKm: 63 }
  ],
  "Istanbul": [
    { iata: "SAW", label: "Istanbul Sabiha Gökçen", distKm: 30 },
    { iata: "IST", label: "İstanbul", distKm: 35 }
  ],
  "Jabal Akhdar": [
    { iata: "MCT", label: "Muscat", distKm: 92 }
  ],
  "Jakarta": [
    { iata: "HLP", label: "Halim Perdanakusuma", distKm: 10 },
    { iata: "CGK", label: "Soekarno-Hatta", distKm: 20 }
  ],
  "Jerusalem": [
    { iata: "TLV", label: "Ben Gurion", distKm: 41 }
  ],
  "Jimbaran Bay": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 4 }
  ],
  "Juan-les-Pins": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 13 }
  ],
  "Kailua-Kona": [
    { iata: "KOA", label: "Ellison Onizuka Kona at Keāhole", distKm: 12 }
  ],
  "Kalafati": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 7 }
  ],
  "Kangaroo Island": [
    { iata: "KGC", label: "Kingscote", distKm: 71 }
  ],
  "Kapalua, Maui": [
    { iata: "JHM", label: "Kapalua", distKm: 5 }
  ],
  "Kapps Farm": [
    { iata: "WDH", label: "Hosea Kutako", distKm: 9 }
  ],
  "Karoso Beach": [
    { iata: "TMC", label: "Tambolaka", distKm: 36 }
  ],
  "Kea Island": [
    { iata: "ATH", label: "Athens Eleftherios Venizelos", distKm: 46 },
    { iata: "JSY", label: "Syros", distKm: 63 }
  ],
  "Khok Kloi": [
    { iata: "HKT", label: "Phuket", distKm: 20 }
  ],
  "Kiawah Island": [
    { iata: "CHS", label: "Charleston", distKm: 33 }
  ],
  "Kihavah": [
    { iata: "DRV", label: "Dharavandhoo", distKm: 17 }
  ],
  "Kingdom of Fife": [
    { iata: "DND", label: "Dundee", distKm: 18 }
  ],
  "Kinigi": [
    { iata: "KXO", label: "Kisoro", distKm: 23 }
  ],
  "Kirawira": [
    { iata: "SEU", label: "Seronera", distKm: 75 },
    { iata: "MUZ", label: "Musoma", distKm: 86 }
  ],
  "Koh Krabey Island": [
    { iata: "KOS", label: "Sihanouk", distKm: 10 }
  ],
  "Koh Lanta": [
    { iata: "TST", label: "Trang", distKm: 60 },
    { iata: "KBV", label: "Krabi", distKm: 67 }
  ],
  "Koh Yao Yai": [
    { iata: "HKT", label: "Phuket", distKm: 33 },
    { iata: "KBV", label: "Krabi", distKm: 42 }
  ],
  "Kohler": [
    { iata: "ATW", label: "Appleton", distKm: 83 },
    { iata: "GRB", label: "Austin Straubel", distKm: 87 }
  ],
  "Kokomo Island": [
    { iata: "KDV", label: "Vunisea", distKm: 48 }
  ],
  "Krabi": [
    { iata: "KBV", label: "Krabi", distKm: 26 }
  ],
  "Krong Siem Reap": [
    { iata: "SAI", label: "Siem Reap-Angkor", distKm: 43 }
  ],
  "Kruger National Park": [
    { iata: "SZK", label: "Skukuza", distKm: 32 }
  ],
  "Kuala Lumpur": [
    { iata: "SZB", label: "Sultan Abdul Aziz Shah", distKm: 18 },
    { iata: "KUL", label: "Kuala Lumpur", distKm: 45 }
  ],
  "Kuda Huraa Island": [
    { iata: "MLE", label: "Velana", distKm: 17 }
  ],
  "Kudadoo Island": [
    { iata: "NMF", label: "Maafaru", distKm: 35 },
    { iata: "DRV", label: "Dharavandhoo", distKm: 51 }
  ],
  "Kunfunadhoo Island": [
    { iata: "DRV", label: "Dharavandhoo", distKm: 8 }
  ],
  "Kyllini": [
    { iata: "ZTH", label: "Zakynthos Dionysios Solomos", distKm: 23 }
  ],
  "Kyoto": [
    { iata: "ITM", label: "Osaka Itami", distKm: 39 }
  ],
  "La Croix-Valmer": [
    { iata: "LTT", label: "La Môle", distKm: 9 }
  ],
  "La Jolla": [
    { iata: "SAN", label: "San Diego", distKm: 20 }
  ],
  "La Manzanilla": [
    { iata: "ZLO", label: "Playa de Oro", distKm: 29 }
  ],
  "Laamu": [
    { iata: "KDO", label: "Kadhdhoo", distKm: 14 }
  ],
  "Laguna Beach": [
    { iata: "SNA", label: "John Wayne Orange County", distKm: 21 }
  ],
  "Lake Louise": [
    { iata: "YYC", label: "Calgary", distKm: 157 },
    { iata: "YXC", label: "Cranbrook/Canadian Rockies", distKm: 203 }
  ],
  "Lake Tahoe": [
    { iata: "TKF", label: "Truckee Tahoe", distKm: 43 },
    { iata: "RNO", label: "Reno Tahoe", distKm: 61 }
  ],
  "Lamego": [
    { iata: "VRL", label: "Vila Real", distKm: 16 }
  ],
  "Lanai City": [
    { iata: "LNY", label: "Lanai", distKm: 5 }
  ],
  "Landaa Giraavaru": [
    { iata: "DRV", label: "Dharavandhoo", distKm: 15 }
  ],
  "Langkawi": [
    { iata: "LGK", label: "Langkawi", distKm: 12 }
  ],
  "Lankanfushi": [
    { iata: "MLE", label: "Velana", distKm: 12 }
  ],
  "Las Vegas": [
    { iata: "LAS", label: "Harry Reid", distKm: 4 }
  ],
  "Laucala Island": [
    { iata: "TVU", label: "Matei", distKm: 22 }
  ],
  "Lausanne": [
    { iata: "GVA", label: "Geneva", distKm: 50 }
  ],
  "Le Baux de Provence": [
    { iata: "AVN", label: "Avignon Caumont", distKm: 21 }
  ],
  "Le Morne Peninsula": [
    { iata: "MRU", label: "Sir Seewoosagur Ramgoolam", distKm: 39 }
  ],
  "Le Puy-Sainte-Réparade": [
    { iata: "MRS", label: "Marseille Provence", distKm: 27 }
  ],
  "Lech Am Arlberg": [
    { iata: "ACH", label: "Sankt Gallen Altenrhein", distKm: 53 },
    { iata: "FDH", label: "Bodensee Friedrichshafen", distKm: 70 }
  ],
  "Les Belleville": [
    { iata: "CMF", label: "Chambéry Aix les Bains", distKm: 58 },
    { iata: "NCY", label: "Annecy Meythet", distKm: 70 }
  ],
  "Lhaviyani Atoll": [
    { iata: "NMF", label: "Maafaru", distKm: 32 }
  ],
  "Lima": [
    { iata: "LIM", label: "Jorge Chávez", distKm: 16 }
  ],
  "Lisbon": [
    { iata: "LIS", label: "Lisbon Humberto Delgado", distKm: 6 },
    { iata: "CAT", label: "Cascais", distKm: 17 }
  ],
  "London": [
    { iata: "LCY", label: "London City", distKm: 14 },
    { iata: "LHR", label: "London Heathrow", distKm: 22 },
    { iata: "LGW", label: "London Gatwick", distKm: 40 },
    { iata: "LTN", label: "London Luton", distKm: 44 },
    { iata: "STN", label: "London Stansted", distKm: 49 },
    { iata: "SEN", label: "London Southend", distKm: 58 }
  ],
  "Long Bay Village": [
    { iata: "AXA", label: "Clayton J. Lloyd", distKm: 9 },
    { iata: "SFG", label: "Grand Case-l'Espérance", distKm: 13 },
    { iata: "SXM", label: "Princess Juliana", distKm: 17 }
  ],
  "Long Island": [
    { iata: "ANU", label: "V. C. Bird", distKm: 4 }
  ],
  "Lord Howe Island": [
    { iata: "LDH", label: "Lord Howe Island", distKm: 1 }
  ],
  "Los Angeles": [
    { iata: "LAX", label: "Los Angeles", distKm: 14 },
    { iata: "BUR", label: "Hollywood Burbank/Bob Hope", distKm: 16 },
    { iata: "HHR", label: "Jack Northrop Field Hawthorne", distKm: 16 }
  ],
  "Los Cabos": [
    { iata: "SJD", label: "Los Cabos", distKm: 10 }
  ],
  "Los Olivos": [
    { iata: "SBA", label: "Santa Barbara", distKm: 37 },
    { iata: "SMX", label: "Santa Maria Public Captain G Allan Hancock Field", distKm: 40 }
  ],
  "Luang Prabang": [
    { iata: "LPQ", label: "Luang Phabang", distKm: 8 }
  ],
  "Lucerne": [
    { iata: "ZRH", label: "Zürich", distKm: 48 },
    { iata: "BRN", label: "Bern", distKm: 64 }
  ],
  "Lugano": [
    { iata: "LUG", label: "Lugano", distKm: 4 }
  ],
  "Maagau Island": [
    { iata: "VAM", label: "Villa Maamigili", distKm: 59 },
    { iata: "TMF", label: "Thimarafushi", distKm: 86 }
  ],
  "Maalifushi": [
    { iata: "TMF", label: "Thimarafushi", distKm: 20 }
  ],
  "Macau": [
    { iata: "MFM", label: "Macau", distKm: 4 },
    { iata: "ZUH", label: "Zhuhai Jinwan", distKm: 25 }
  ],
  "Madrid": [
    { iata: "MAD", label: "Adolfo Suárez Madrid-Barajas", distKm: 13 }
  ],
  "Majorca": [
    { iata: "PMI", label: "Palma de Mallorca", distKm: 16 }
  ],
  "Malaga": [
    { iata: "AGP", label: "Málaga-Costa del Sol", distKm: 10 }
  ],
  "Maldives": [
    { iata: "HDK", label: "Kulhudhuffushi", distKm: 59 },
    { iata: "FND", label: "Funadhoo", distKm: 74 }
  ],
  "Maldonado": [
    { iata: "PDP", label: "Capitan Corbeta CA Curbelo", distKm: 19 }
  ],
  "Mangis": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 48 }
  ],
  "Manila": [
    { iata: "MNL", label: "Ninoy Aquino", distKm: 4 }
  ],
  "Marana": [
    { iata: "TUS", label: "Tucson", distKm: 43 }
  ],
  "Marbella": [
    { iata: "AGP", label: "Málaga-Costa del Sol", distKm: 42 },
    { iata: "GIB", label: "Gibraltar", distKm: 55 }
  ],
  "Marigot": [
    { iata: "SXM", label: "Princess Juliana", distKm: 4 },
    { iata: "SFG", label: "Grand Case-l'Espérance", distKm: 11 },
    { iata: "AXA", label: "Clayton J. Lloyd", distKm: 19 }
  ],
  "Marmaris": [
    { iata: "RHO", label: "Rhodes \"Diagoras\"", distKm: 40 }
  ],
  "Marrakech": [
    { iata: "RAK", label: "Marrakesh Menara", distKm: 6 }
  ],
  "Mashpi": [
    { iata: "UIO", label: "Mariscal Sucre", distKm: 67 }
  ],
  "Matauri Bay": [
    { iata: "KKE", label: "Kerikeri", distKm: 20 }
  ],
  "Maui": [
    { iata: "OGG", label: "Kahului", distKm: 24 }
  ],
  "Maundays Bay": [
    { iata: "AXA", label: "Clayton J. Lloyd", distKm: 10 },
    { iata: "SFG", label: "Grand Case-l'Espérance", distKm: 12 },
    { iata: "SXM", label: "Princess Juliana", distKm: 14 }
  ],
  "Mazzarò": [
    { iata: "REG", label: "Reggio Calabria", distKm: 39 },
    { iata: "CTA", label: "Catania-Fontanarossa", distKm: 48 }
  ],
  "Medhufaru Island": [
    { iata: "NMF", label: "Maafaru", distKm: 12 }
  ],
  "Megali Ammos": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 2 }
  ],
  "Megeve": [
    { iata: "NCY", label: "Annecy Meythet", distKm: 41 },
    { iata: "GVA", label: "Geneva", distKm: 58 }
  ],
  "Melbourne": [
    { iata: "MEB", label: "Melbourne Essendon", distKm: 12 },
    { iata: "MEL", label: "Melbourne", distKm: 20 },
    { iata: "MBW", label: "Melbourne Moorabbin", distKm: 21 },
    { iata: "AVV", label: "Melbourne Avalon", distKm: 50 }
  ],
  "Menlo Park": [
    { iata: "SQL", label: "San Carlos", distKm: 11 }
  ],
  "Meradhoo Island": [
    { iata: "KDM", label: "Kaadedhdhoo", distKm: 15 }
  ],
  "Merano": [
    { iata: "BZO", label: "Bolzano", distKm: 23 }
  ],
  "Mexico City": [
    { iata: "MEX", label: "Mexico City Benito Juárez", distKm: 11 },
    { iata: "NLU", label: "Felipe Ángeles", distKm: 39 }
  ],
  "Miami": [
    { iata: "MIA", label: "Miami", distKm: 6 },
    { iata: "OPF", label: "Miami-Opa Locka Executive", distKm: 18 }
  ],
  "Miami Beach": [
    { iata: "MIA", label: "Miami", distKm: 17 },
    { iata: "OPF", label: "Miami-Opa Locka Executive", distKm: 18 }
  ],
  "Milan": [
    { iata: "LIN", label: "Milano Linate", distKm: 7 },
    { iata: "MXP", label: "Milan Malpensa", distKm: 40 }
  ],
  "Milas": [
    { iata: "BJV", label: "Milas Bodrum", distKm: 23 }
  ],
  "Mitzpe Ramon": [
    { iata: "ETM", label: "Ramon", distKm: 100 },
    { iata: "AAC", label: "El Arish", distKm: 106 }
  ],
  "Miyako Island": [
    { iata: "MMY", label: "Miyako", distKm: 7 },
    { iata: "SHI", label: "Shimojishima", distKm: 14 }
  ],
  "Mnemba": [
    { iata: "ZNZ", label: "Abeid Amani Karume", distKm: 48 }
  ],
  "Molatedi": [
    { iata: "GBE", label: "Sir Seretse Khama", distKm: 48 }
  ],
  "Moltrasio": [
    { iata: "LUG", label: "Lugano", distKm: 22 }
  ],
  "Mont-Peleron": [
    { iata: "GVA", label: "Geneva", distKm: 61 },
    { iata: "BRN", label: "Bern", distKm: 70 }
  ],
  "Montalcino": [
    { iata: "FLR", label: "Florence, Peretola", distKm: 82 },
    { iata: "PEG", label: "Perugia San Francesco d'Assisi - Umbria", distKm: 89 }
  ],
  "Monte Carlo": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 19 }
  ],
  "Montecito": [
    { iata: "SBA", label: "Santa Barbara", distKm: 19 }
  ],
  "Montego Bay": [
    { iata: "MBJ", label: "Sangster", distKm: 29 }
  ],
  "Montreal": [
    { iata: "YHU", label: "Montréal / Saint-Hubert Metropolitan", distKm: 13 },
    { iata: "YUL", label: "Montreal / Pierre Elliott Trudeau", distKm: 13 },
    { iata: "YMX", label: "Montreal Mirabel", distKm: 41 }
  ],
  "Montreux": [
    { iata: "GVA", label: "Geneva", distKm: 65 },
    { iata: "BRN", label: "Bern", distKm: 69 }
  ],
  "Moscow": [
    { iata: "VKO", label: "Vnukovo", distKm: 16 },
    { iata: "SVO", label: "Sheremetyevo", distKm: 28 },
    { iata: "DME", label: "Domodedovo", distKm: 55 },
    { iata: "ZIA", label: "Zhukovsky", distKm: 60 }
  ],
  "Moskito Island": [
    { iata: "VIJ", label: "Virgin Gorda", distKm: 9 },
    { iata: "EIS", label: "Terrance B. Lettsome", distKm: 18 }
  ],
  "Mossman": [
    { iata: "CNS", label: "Cairns", distKm: 63 }
  ],
  "Moyo Island": [
    { iata: "SWQ", label: "Sultan Muhammad Kaharuddin III", distKm: 27 }
  ],
  "Muang Muang Krabi": [
    { iata: "KBV", label: "Krabi", distKm: 27 }
  ],
  "Mumbai": [
    { iata: "BOM", label: "Chhatrapati Shivaji Maharaj", distKm: 15 }
  ],
  "Munich": [
    { iata: "MUC", label: "Munich", distKm: 28 }
  ],
  "Muravandhoo": [
    { iata: "DRV", label: "Dharavandhoo", distKm: 54 },
    { iata: "NMF", label: "Maafaru", distKm: 62 }
  ],
  "Muscat": [
    { iata: "MCT", label: "Muscat", distKm: 18 }
  ],
  "Mykonos Town": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 2 }
  ],
  "Namiri Plains": [
    { iata: "MRE", label: "Mara Serena Lodge Airstrip", distKm: 23 }
  ],
  "Nanjing": [
    { iata: "NKG", label: "Nanjing Lukou", distKm: 35 }
  ],
  "Napa Valley": [
    { iata: "CCR", label: "Buchanan Field", distKm: 35 }
  ],
  "Naples": [
    { iata: "NAP", label: "Naples", distKm: 7 }
  ],
  "Nassau": [
    { iata: "NAS", label: "Lynden Pindling", distKm: 8 }
  ],
  "Natales": [
    { iata: "PNT", label: "Lieutenant Julio Gallardo", distKm: 2 },
    { iata: "RYO", label: "28 de Noviembre", distKm: 24 }
  ],
  "Necker Island": [
    { iata: "VIJ", label: "Virgin Gorda", distKm: 11 },
    { iata: "EIS", label: "Terrance B. Lettsome", distKm: 21 }
  ],
  "Neuvecelle": [
    { iata: "GVA", label: "Geneva", distKm: 41 }
  ],
  "New Delhi": [
    { iata: "DEL", label: "Indira Gandhi", distKm: 15 },
    { iata: "HDO", label: "Hindon / Hindon Air Force Station", distKm: 17 }
  ],
  "New Orleans": [
    { iata: "MSY", label: "Louis Armstrong New Orleans", distKm: 20 }
  ],
  "New York": [
    { iata: "LGA", label: "LaGuardia", distKm: 10 },
    { iata: "EWR", label: "Newark Liberty", distKm: 17 },
    { iata: "JFK", label: "John F. Kennedy", distKm: 22 }
  ],
  "Newport Coast": [
    { iata: "SNA", label: "John Wayne Orange County", distKm: 10 }
  ],
  "Nice": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 7 }
  ],
  "Nihiwatu Beach": [
    { iata: "TMC", label: "Tambolaka", distKm: 44 }
  ],
  "Nikiti": [
    { iata: "SKG", label: "Thessaloniki Macedonia", distKm: 65 }
  ],
  "Nikko": [
    { iata: "FKS", label: "Fukushima", distKm: 99 },
    { iata: "IBR", label: "Ibaraki", distKm: 103 }
  ],
  "Ninh Van Bay": [
    { iata: "CXR", label: "Cam Ranh / Cam Ranh Air Base", distKm: 41 }
  ],
  "North Island": [
    { iata: "SEZ", label: "Seychelles", distKm: 44 },
    { iata: "PRI", label: "Praslin Island", distKm: 50 }
  ],
  "Nusa Dua": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 10 }
  ],
  "Obbürgen": [
    { iata: "ZRH", label: "Zürich", distKm: 53 },
    { iata: "BRN", label: "Bern", distKm: 67 }
  ],
  "Oia": [
    { iata: "JTR", label: "Santorini", distKm: 10 }
  ],
  "Okavango Delta": [
    { iata: "MUB", label: "Maun", distKm: 100 },
    { iata: "SWX", label: "Shakawe", distKm: 145 }
  ],
  "Olhuveli": [
    { iata: "TMF", label: "Thimarafushi", distKm: 58 }
  ],
  "Ornos": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 3 }
  ],
  "Osaka": [
    { iata: "ITM", label: "Osaka Itami", distKm: 12 },
    { iata: "KIX", label: "Kansai", distKm: 37 }
  ],
  "Oslo": [
    { iata: "OSL", label: "Oslo-Gardermoen", distKm: 38 }
  ],
  "Palermo": [
    { iata: "PMO", label: "Falcone-Borsellino", distKm: 25 }
  ],
  "Palm Beach": [
    { iata: "PBI", label: "President Donald J. Trump", distKm: 7 }
  ],
  "Palma de Mallorca": [
    { iata: "PMI", label: "Palma de Mallorca", distKm: 12 }
  ],
  "Palmetto Bluff": [
    { iata: "HHH", label: "Hilton Head", distKm: 18 }
  ],
  "Pamalican Island": [
    { iata: "CYU", label: "Cuyo", distKm: 67 }
  ],
  "Pamushana": [
    { iata: "VPY", label: "Chimoio", distKm: 266 },
    { iata: "PHW", label: "Hendrik Van Eck", distKm: 329 }
  ],
  "Papas Beach": [
    { iata: "JTR", label: "Santorini", distKm: 33 },
    { iata: "JNX", label: "Naxos Island National", distKm: 44 }
  ],
  "Paphos": [
    { iata: "PFO", label: "Paphos", distKm: 7 }
  ],
  "Paradise Island": [
    { iata: "NAS", label: "Lynden Pindling", distKm: 16 }
  ],
  "Paris": [
    { iata: "LBG", label: "Paris-Le Bourget", distKm: 14 },
    { iata: "ORY", label: "Paris-Orly", distKm: 16 },
    { iata: "CDG", label: "Charles de Gaulle", distKm: 24 }
  ],
  "Park City": [
    { iata: "SLC", label: "Salt Lake City", distKm: 46 },
    { iata: "PVU", label: "Provo", distKm: 51 }
  ],
  "Paro": [
    { iata: "PBH", label: "Paro", distKm: 8 }
  ],
  "Patong": [
    { iata: "HKT", label: "Phuket", distKm: 26 }
  ],
  "Perez Zeledón": [
    { iata: "XQP", label: "Quepos Managua", distKm: 62 },
    { iata: "GLF", label: "Golfito", distKm: 87 }
  ],
  "Perthshire": [
    { iata: "EDI", label: "Edinburgh", distKm: 44 },
    { iata: "DND", label: "Dundee", distKm: 49 }
  ],
  "Perugia": [
    { iata: "PEG", label: "Perugia San Francesco d'Assisi - Umbria", distKm: 32 }
  ],
  "Petit Anse bay": [
    { iata: "SEZ", label: "Seychelles", distKm: 11 }
  ],
  "Philadelphia": [
    { iata: "PHL", label: "Philadelphia", distKm: 11 }
  ],
  "Philipsburg": [
    { iata: "MSO", label: "Missoula Montana", distKm: 85 },
    { iata: "BTM", label: "Bert Mooney", distKm: 86 }
  ],
  "Phnom Penh": [
    { iata: "KTI", label: "Techo", distKm: 24 }
  ],
  "Phoenix": [
    { iata: "PHX", label: "Phoenix Sky Harbor", distKm: 10 }
  ],
  "Pine Cay": [
    { iata: "NCA", label: "North Caicos", distKm: 17 },
    { iata: "PLS", label: "Providenciales", distKm: 21 }
  ],
  "Platis Gialos Beach": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 2 }
  ],
  "Playa del Carmen": [
    { iata: "CZM", label: "Cozumel", distKm: 21 }
  ],
  "Porto Ercole": [
    { iata: "EBA", label: "Marina di Campo", distKm: 89 },
    { iata: "FCO", label: "Rome-Fiumicino Leonardo da Vinci", distKm: 108 }
  ],
  "Portofino": [
    { iata: "GOA", label: "Genoa Cristoforo Colombo", distKm: 32 }
  ],
  "Portonovi": [
    { iata: "TIV", label: "Tivat", distKm: 11 }
  ],
  "Positano": [
    { iata: "NAP", label: "Naples", distKm: 34 },
    { iata: "QSR", label: "Salerno Costa d'Amalfi", distKm: 35 }
  ],
  "Poste De Flacq": [
    { iata: "MRU", label: "Sir Seewoosagur Ramgoolam", distKm: 31 }
  ],
  "Prague": [
    { iata: "PRG", label: "Václav Havel Prague", distKm: 12 }
  ],
  "Princeville": [
    { iata: "LIH", label: "Lihue", distKm: 32 }
  ],
  "Providenciales": [
    { iata: "PLS", label: "Providenciales", distKm: 12 }
  ],
  "Psarou": [
    { iata: "JMK", label: "Mykonos Island National", distKm: 2 }
  ],
  "Puigpunyent": [
    { iata: "PMI", label: "Palma de Mallorca", distKm: 20 }
  ],
  "Puligny-Montrachet": [
    { iata: "DIJ", label: "Dijon Longvic", distKm: 44 },
    { iata: "DLE", label: "Dole Tavaux", distKm: 52 }
  ],
  "Punakha": [
    { iata: "PBH", label: "Paro", distKm: 45 }
  ],
  "Punta Mita": [
    { iata: "PVR", label: "Puerto Vallarta", distKm: 31 }
  ],
  "Pylos": [
    { iata: "KLX", label: "Kalamata", distKm: 31 }
  ],
  "Queenstown": [
    { iata: "ZQN", label: "Queenstown", distKm: 10 }
  ],
  "Quintana Roo": [
    { iata: "CZM", label: "Cozumel", distKm: 24 }
  ],
  "Quito": [
    { iata: "UIO", label: "Mariscal Sucre", distKm: 21 }
  ],
  "Ramatuelle": [
    { iata: "LTT", label: "La Môle", distKm: 14 }
  ],
  "Rancho Santa Fe": [
    { iata: "CLD", label: "McClellan-Palomar", distKm: 18 }
  ],
  "Randheli": [
    { iata: "NMF", label: "Maafaru", distKm: 20 }
  ],
  "Rangali Island": [
    { iata: "VAM", label: "Villa Maamigili", distKm: 20 }
  ],
  "Ravello": [
    { iata: "QSR", label: "Salerno Costa d'Amalfi", distKm: 25 },
    { iata: "NAP", label: "Naples", distKm: 38 }
  ],
  "Reethi Rah Island": [
    { iata: "MLE", label: "Velana", distKm: 41 }
  ],
  "Rendezvous Bay": [
    { iata: "AXA", label: "Clayton J. Lloyd", distKm: 7 },
    { iata: "SFG", label: "Grand Case-l'Espérance", distKm: 11 },
    { iata: "SXM", label: "Princess Juliana", distKm: 15 }
  ],
  "Reykjavik": [
    { iata: "RKV", label: "Reykjavík", distKm: 2 },
    { iata: "KEF", label: "Keflavik", distKm: 37 }
  ],
  "Rio de Janeiro": [
    { iata: "SDU", label: "Santos Dumont", distKm: 8 },
    { iata: "RRJ", label: "Jacarepaguá - Roberto Marinho", distKm: 19 },
    { iata: "GIG", label: "Rio Galeão - Tom Jobim", distKm: 20 }
  ],
  "Rio Negro": [
    { iata: "BRC", label: "Teniente Luis Candelaria", distKm: 33 }
  ],
  "Rio San Juan": [
    { iata: "AZS", label: "Samaná El Catey", distKm: 54 },
    { iata: "POP", label: "Gregorio Luperon", distKm: 58 }
  ],
  "Rippon": [
    { iata: "LBA", label: "Leeds Bradford", distKm: 28 }
  ],
  "Riviera Maya": [
    { iata: "CZM", label: "Cozumel", distKm: 28 },
    { iata: "CUN", label: "Cancún", distKm: 32 }
  ],
  "Riyadh": [
    { iata: "RUH", label: "King Khalid", distKm: 30 }
  ],
  "Rome": [
    { iata: "CIA", label: "Ciampino-G. B. Pastine", distKm: 15 },
    { iata: "FCO", label: "Rome-Fiumicino Leonardo da Vinci", distKm: 22 }
  ],
  "Roquebrune-Cap-Martin": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 21 }
  ],
  "Rovinj": [
    { iata: "PUY", label: "Pula", distKm: 30 }
  ],
  "Ruhengeri": [
    { iata: "KXO", label: "Kisoro", distKm: 28 },
    { iata: "GOM", label: "Goma", distKm: 40 }
  ],
  "Rutherford": [
    { iata: "STS", label: "Charles M. Schulz Sonoma County", distKm: 35 }
  ],
  "Sabi Sand Reserve": [
    { iata: "SZK", label: "Skukuza", distKm: 12 }
  ],
  "Saint-Tropez": [
    { iata: "LTT", label: "La Môle", distKm: 14 }
  ],
  "Salzburg": [
    { iata: "SZG", label: "Salzburg", distKm: 19 }
  ],
  "San Francisco": [
    { iata: "OAK", label: "Oakland San Francisco Bay", distKm: 18 },
    { iata: "SFO", label: "San Francisco", distKm: 19 }
  ],
  "San Jose del Cabo": [
    { iata: "SJD", label: "Los Cabos", distKm: 15 },
    { iata: "CSW", label: "Cabo San Lucas", distKm: 25 }
  ],
  "San Miguel de Allende": [
    { iata: "QRO", label: "Querétaro Intercontinental", distKm: 66 },
    { iata: "BJX", label: "Guanajuato", distKm: 77 }
  ],
  "San Remo": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 48 }
  ],
  "Sant Joan de Labritja": [
    { iata: "IBZ", label: "Ibiza", distKm: 29 }
  ],
  "Sant Josep de Sa Talaia": [
    { iata: "IBZ", label: "Ibiza", distKm: 16 }
  ],
  "Santa Fe": [
    { iata: "SAF", label: "Santa Fe", distKm: 20 }
  ],
  "Santa Monica": [
    { iata: "LAX", label: "Los Angeles", distKm: 10 },
    { iata: "HHR", label: "Jack Northrop Field Hawthorne", distKm: 17 }
  ],
  "Santiago": [
    { iata: "SCL", label: "Comodoro Arturo Merino Benítez", distKm: 16 }
  ],
  "Sanya": [
    { iata: "SYX", label: "Sanya Phoenix", distKm: 23 }
  ],
  "Sao Goncalo do Amarante": [
    { iata: "FOR", label: "Pinto Martins", distKm: 51 }
  ],
  "Sao Paulo": [
    { iata: "CGH", label: "Congonhas-Deputado Freitas Nobre", distKm: 8 },
    { iata: "GRU", label: "São Paulo/Guarulhos-Governor André Franco Montoro", distKm: 24 }
  ],
  "Savannah": [
    { iata: "SAV", label: "Savannah Hilton Head", distKm: 13 }
  ],
  "Scottsdale": [
    { iata: "PHX", label: "Phoenix Sky Harbor", distKm: 36 },
    { iata: "AZA", label: "Mesa Gateway", distKm: 51 }
  ],
  "Sea Island": [
    { iata: "BQK", label: "Brunswick Golden Isles", distKm: 14 }
  ],
  "Seattle": [
    { iata: "BFI", label: "King County - Boeing Field", distKm: 9 },
    { iata: "SEA", label: "Seattle-Tacoma", distKm: 18 },
    { iata: "PAE", label: "Seattle Paine Field", distKm: 33 }
  ],
  "Seoul": [
    { iata: "GMP", label: "Seoul Gimpo", distKm: 16 },
    { iata: "ICN", label: "Incheon", distKm: 48 }
  ],
  "Serengeti": [
    { iata: "SEU", label: "Seronera", distKm: 27 }
  ],
  "Sesriem": [
    { iata: "LUD", label: "Luderitz", distKm: 222 },
    { iata: "WVB", label: "Walvis Bay", distKm: 237 }
  ],
  "Seven Mile Beach": [
    { iata: "GCM", label: "Owen Roberts", distKm: 5 }
  ],
  "Seville": [
    { iata: "SVQ", label: "Seville", distKm: 10 }
  ],
  "Shanghai": [
    { iata: "SHA", label: "Shanghai Hongqiao", distKm: 13 },
    { iata: "PVG", label: "Shanghai Pudong", distKm: 33 }
  ],
  "Sharm El Sheikh": [
    { iata: "SSH", label: "Sharm El Sheikh", distKm: 2 }
  ],
  "Shenzhen": [
    { iata: "SZX", label: "Shenzhen Bao'an", distKm: 29 }
  ],
  "Sidemen Valley": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 43 }
  ],
  "Singapore": [
    { iata: "XSP", label: "Seletar", distKm: 15 },
    { iata: "SIN", label: "Singapore Changi", distKm: 18 }
  ],
  "Skukuza Rest Camp": [
    { iata: "SZK", label: "Skukuza", distKm: 4 }
  ],
  "Sonop Farm": [
    { iata: "LUD", label: "Luderitz", distKm: 162 }
  ],
  "Sorrento": [
    { iata: "NAP", label: "Naples", distKm: 30 }
  ],
  "Sourfriere": [
    { iata: "UVF", label: "Hewanorra", distKm: 16 },
    { iata: "SLU", label: "George F. L. Charles", distKm: 23 }
  ],
  "Spanish Town": [
    { iata: "VIJ", label: "Virgin Gorda", distKm: 2 },
    { iata: "EIS", label: "Terrance B. Lettsome", distKm: 11 }
  ],
  "St. Andrews": [
    { iata: "DND", label: "Dundee", distKm: 18 }
  ],
  "St. Barthelemy": [
    { iata: "SBH", label: "St. Jean", distKm: 1 }
  ],
  "St. James": [
    { iata: "BGI", label: "Grantley Adams", distKm: 19 }
  ],
  "St. Moritz": [
    { iata: "LUG", label: "Lugano", distKm: 91 },
    { iata: "BGY", label: "Il Caravaggio", distKm: 92 }
  ],
  "Stockholm": [
    { iata: "BMA", label: "Stockholm-Bromma", distKm: 8 },
    { iata: "ARN", label: "Stockholm-Arlanda", distKm: 36 }
  ],
  "Stresa": [
    { iata: "LUG", label: "Lugano", distKm: 33 },
    { iata: "MXP", label: "Milan Malpensa", distKm: 33 }
  ],
  "Sunningdale": [
    { iata: "LHR", label: "London Heathrow", distKm: 13 }
  ],
  "Sunny Isles Beach": [
    { iata: "FLL", label: "Fort Lauderdale Hollywood", distKm: 15 },
    { iata: "OPF", label: "Miami-Opa Locka Executive", distKm: 16 },
    { iata: "MIA", label: "Miami", distKm: 23 }
  ],
  "Surfers Paradise": [
    { iata: "OOL", label: "Gold Coast", distKm: 18 }
  ],
  "Surfside": [
    { iata: "OPF", label: "Miami-Opa Locka Executive", distKm: 16 },
    { iata: "MIA", label: "Miami", distKm: 19 },
    { iata: "FLL", label: "Fort Lauderdale Hollywood", distKm: 22 }
  ],
  "Sydney": [
    { iata: "SYD", label: "Sydney Kingsford Smith", distKm: 10 }
  ],
  "Taipei": [
    { iata: "TSA", label: "Taipei Songshan", distKm: 1 }
  ],
  "Tangier": [
    { iata: "TNG", label: "Tangier Ibn Battuta", distKm: 11 }
  ],
  "Taormina": [
    { iata: "REG", label: "Reggio Calabria", distKm: 40 },
    { iata: "CTA", label: "Catania-Fontanarossa", distKm: 47 }
  ],
  "Te Awanga": [
    { iata: "NPE", label: "Hawke's Bay", distKm: 26 }
  ],
  "Tel Aviv": [
    { iata: "TLV", label: "Ben Gurion", distKm: 13 }
  ],
  "Tenerife South": [
    { iata: "TFS", label: "Tenerife Sur", distKm: 17 }
  ],
  "Tepic-Puerto Vallarta": [
    { iata: "PVR", label: "Puerto Vallarta", distKm: 34 }
  ],
  "Teton Village": [
    { iata: "JAC", label: "Jackson Hole", distKm: 7 }
  ],
  "Thalang": [
    { iata: "HKT", label: "Phuket", distKm: 18 }
  ],
  "Thiladhoo Island": [
    { iata: "DRV", label: "Dharavandhoo", distKm: 12 }
  ],
  "Tokyo": [
    { iata: "HND", label: "Tokyo Haneda", distKm: 14 }
  ],
  "Torno": [
    { iata: "LUG", label: "Lugano", distKm: 23 }
  ],
  "Toronto": [
    { iata: "YTZ", label: "Billy Bishop Toronto City", distKm: 2 },
    { iata: "YYZ", label: "Toronto Pearson", distKm: 19 }
  ],
  "Torres Del Paine": [
    { iata: "RYO", label: "28 de Noviembre", distKm: 75 },
    { iata: "PNT", label: "Lieutenant Julio Gallardo", distKm: 78 }
  ],
  "Tourrettes": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 40 },
    { iata: "LTT", label: "La Môle", distKm: 47 }
  ],
  "Tragaki Beach": [
    { iata: "ZTH", label: "Zakynthos Dionysios Solomos", distKm: 9 }
  ],
  "Trancoso": [
    { iata: "BPS", label: "Porto Seguro", distKm: 20 }
  ],
  "Tremezzina": [
    { iata: "LUG", label: "Lugano", distKm: 25 }
  ],
  "Trondheim": [
    { iata: "TRD", label: "Trondheim, Værnes", distKm: 26 }
  ],
  "Truckee": [
    { iata: "TKF", label: "Truckee Tahoe", distKm: 6 }
  ],
  "Tswalu Kalahari Reserve": [
    { iata: "SIS", label: "Sishen", distKm: 69 }
  ],
  "Turtle Island": [
    { iata: "YAS", label: "Yasawa Island", distKm: 30 }
  ],
  "Ubud": [
    { iata: "DPS", label: "Denpasar I Gusti Ngurah Rai", distKm: 31 }
  ],
  "Udaipur": [
    { iata: "UDR", label: "Maharana Pratap", distKm: 22 }
  ],
  "Uluru-Kata Tjuta National Park": [
    { iata: "AYQ", label: "Ayers Rock Connellan", distKm: 8 }
  ],
  "Ummahat Islands": [
    { iata: "RSI", label: "Red Sea", distKm: 34 }
  ],
  "Val d'Isere": [
    { iata: "TRN", label: "Turin", distKm: 59 },
    { iata: "NCY", label: "Annecy Meythet", distKm: 87 }
  ],
  "Vallee": [
    { iata: "FSC", label: "Figari Sud-Corse", distKm: 12 }
  ],
  "Vancouver": [
    { iata: "YVR", label: "Vancouver", distKm: 11 }
  ],
  "Velaa": [
    { iata: "NMF", label: "Maafaru", distKm: 29 },
    { iata: "FND", label: "Funadhoo", distKm: 38 }
  ],
  "Vence": [
    { iata: "NCE", label: "Nice-Côte d'Azur", distKm: 12 }
  ],
  "Venice": [
    { iata: "VCE", label: "Venice Marco Polo", distKm: 8 }
  ],
  "Versailles": [
    { iata: "ORY", label: "Paris-Orly", distKm: 19 }
  ],
  "Vevey": [
    { iata: "GVA", label: "Geneva", distKm: 62 },
    { iata: "BRN", label: "Bern", distKm: 71 }
  ],
  "Vienna": [
    { iata: "VIE", label: "Vienna", distKm: 18 }
  ],
  "Vinh Hy Village": [
    { iata: "CXR", label: "Cam Ranh / Cam Ranh Air Base", distKm: 32 }
  ],
  "Vitznau": [
    { iata: "ZRH", label: "Zürich", distKm: 50 }
  ],
  "Voavah": [
    { iata: "DRV", label: "Dharavandhoo", distKm: 19 }
  ],
  "Vommuli Island": [
    { iata: "VAM", label: "Villa Maamigili", distKm: 62 },
    { iata: "TMF", label: "Thimarafushi", distKm: 84 }
  ],
  "Vouliagmeni": [
    { iata: "ATH", label: "Athens Eleftherios Venizelos", distKm: 21 }
  ],
  "Wanship": [
    { iata: "SLC", label: "Salt Lake City", distKm: 45 },
    { iata: "OGD", label: "Ogden Hinckley", distKm: 64 }
  ],
  "Warsaw": [
    { iata: "WAW", label: "Warsaw Chopin", distKm: 9 },
    { iata: "WMI", label: "Warsaw Modlin", distKm: 34 }
  ],
  "Washington": [
    { iata: "IAD", label: "Washington Dulles", distKm: 66 },
    { iata: "CHO", label: "Charlottesville Albemarle", distKm: 69 }
  ],
  "Washington D.C.": [
    { iata: "DCA", label: "Ronald Reagan Washington National", distKm: 4 }
  ],
  "Washington, D.C.": [
    { iata: "DCA", label: "Ronald Reagan Washington National", distKm: 6 }
  ],
  "Watch Hill": [
    { iata: "WST", label: "Westerly State", distKm: 6 }
  ],
  "West End": [
    { iata: "AXA", label: "Clayton J. Lloyd", distKm: 10 },
    { iata: "SFG", label: "Grand Case-l'Espérance", distKm: 14 },
    { iata: "SXM", label: "Princess Juliana", distKm: 16 }
  ],
  "West Hollywood": [
    { iata: "BUR", label: "Hollywood Burbank/Bob Hope", distKm: 12 },
    { iata: "LAX", label: "Los Angeles", distKm: 17 },
    { iata: "HHR", label: "Jack Northrop Field Hawthorne", distKm: 19 }
  ],
  "Whistler": [
    { iata: "YVR", label: "Vancouver", distKm: 104 },
    { iata: "YPW", label: "Powell River", distKm: 115 }
  ],
  "Williamsburg": [
    { iata: "PHF", label: "Newport News Williamsburg", distKm: 24 }
  ],
  "Yangon": [
    { iata: "RGN", label: "Yangon", distKm: 16 }
  ],
  "Yao Noi": [
    { iata: "HKT", label: "Phuket", distKm: 34 },
    { iata: "KBV", label: "Krabi", distKm: 40 }
  ],
  "Zanzibar": [
    { iata: "ZNZ", label: "Abeid Amani Karume", distKm: 8 }
  ],
  "Zermatt": [
    { iata: "MXP", label: "Milan Malpensa", distKm: 87 },
    { iata: "LUG", label: "Lugano", distKm: 90 }
  ],
  "Zurich": [
    { iata: "ZRH", label: "Zürich", distKm: 10 }
  ],
};

function normalizeCityKey(city: string): string {
  return city.trim().toLowerCase();
}

const LOOKUP: Record<string, CityAirport[]> = Object.fromEntries(
  Object.entries(CITY_AIRPORTS).map(([city, airports]) => [normalizeCityKey(city), airports])
);

/** Nearest airport(s) for a hotel destination city, per the OLTRA hotels
 * collection. Empty array if the city isn't in the mapping (falls back to
 * "please be more specific" in the caller). */
export function getAirportsForCity(city: string): CityAirport[] {
  if (!city) return [];
  return LOOKUP[normalizeCityKey(city)] ?? [];
}
